local util = require "util"

-- the SEND_DATA_SETUP_ST and SEND_DATA_RECOVER_ST states allow a margin of one clock cycle for the switching of the drive direction

return function(settings, flat)
    local lines = util.make_lines_insert()
    local prefix = flat and "_control_" or ""
    if not flat then -- module header
        lines:add("module serial_ctrl")
        lines:add("(")
        lines:add("    input clk,")
        lines:add("    input data_in,")
        lines:add("    output wire write,")
        lines:add("    input data_ready,")
        lines:add("    input reset_internal,")
        lines:add("    output enable_data_counter,")
        lines:add("    output wire update_shift_register,")
        lines:add("    output wire reset_shift_register,")
        lines:add("    output wire enable_shift_register,")
        lines:add("    output wire write_shift_register")
        lines:add(");")
    else
        lines:add("    // control module")
    end
    lines:add("    // control part state machine")
    lines:add("    // states are coded in order to minimize instance count")
    lines:add("    localparam")
    lines:add("        RECEIVE_DATA_ST      = 3'b010,  // receiving data")
    lines:add("        SEND_DATA_ST         = 3'b000,  // sending data")
    lines:add("        WAIT_FOR_COMMAND_ST  = 3'b100,  // wait for command")
    lines:add("        SEND_DATA_SETUP_ST   = 3'b110,  // sending data, setup tristate buffer")
    lines:add("        UPDATE_ST            = 3'b011,  // update shift register")
    lines:add("        RESET_REGISTER_ST    = 3'b111,  // reset shift register")
    lines:add("        SEND_DATA_RECOVER_ST = 3'b001,  // recover from write/read shift to prevent glitches")
    lines:add("        FLUSH_COMMAND_ST     = 3'b101;  // flush command register for idle state")
    lines:add("")
    lines:add("    reg [2:0] %scurr_state_pre;  // changes with posedge", prefix)
    lines:add("    reg [2:0] %scurr_state;      // changes with negedge", prefix)
    lines:add("    reg %sreset_flag_pre;        // changes with negedge", prefix)
    lines:add("    reg %sreset_flag;            // changes with negedge", prefix)
    lines:add("")
    lines:add("    // enable write")
    lines:add("    assign write = (%scurr_state == SEND_DATA_ST);", prefix)
    lines:add("")
    lines:add("    // enable writing to shift register")
    lines:add("    assign write_shift_register = (%scurr_state == RECEIVE_DATA_ST);", prefix)
    lines:add("")
    lines:add("    // enable shifting of shift register")
    lines:add("    assign enable_shift_register = write || write_shift_register;")
    lines:add("")
    lines:add("    // reset shift register (synchronous reset, triggered by the update signal)")
    lines:add("    assign reset_shift_register = !(%scurr_state == RESET_REGISTER_ST);", prefix)
    lines:add("")
    lines:add("    // update shift register")
    lines:add("    assign update_shift_register = (%scurr_state == UPDATE_ST) || (%scurr_state == RESET_REGISTER_ST);", prefix, prefix)
    lines:add("")
    lines:add("    // reset counter")
    lines:add("    assign enable_data_counter = (%scurr_state == RECEIVE_DATA_ST) || (%scurr_state == SEND_DATA_ST);", prefix, prefix)
    lines:add("")
    lines:add("    // command register")
    lines:add("    wire %sreceive_command;", prefix)
    lines:add("    assign %sreceive_command = !%sreset_flag && (%scurr_state == WAIT_FOR_COMMAND_ST);", prefix, prefix, prefix)
    lines:add("    wire %scommand_ready;", prefix)
    lines:add("    wire %scommand_empty;", prefix)
    lines:add("    wire [%d:0] %scommand;", settings.commands_length - 1, prefix)
    lines:add("    reg [%d:0] %scmd_reg;", settings.commands_length + settings.start_pattern_length - 1, prefix)
    lines:add("    reg [%d:0] %scmd_reg_pre;", settings.commands_length + settings.start_pattern_length - 1, prefix)
    lines:add("    assign %scommand_empty = %scmd_reg == 0;", prefix, prefix)
    lines:add("    assign %scommand_ready =", prefix)
    for i = 1, settings.start_pattern_length do
        local line = {}
        table.insert(line, string.format("        %scmd_reg[%d] == 1'b%d", prefix, settings.commands_length +  settings.start_pattern_length - i, settings.start_pattern[i]))
        if i ~= settings.start_pattern_length then
            table.insert(line, " &&")
        else
            table.insert(line, ";")
        end
        lines:add(table.concat(line))
    end
    lines:add("    assign %scommand = %scmd_reg[%d:0];", prefix, prefix, settings.commands_length - 1)
    lines:add("    always @ (negedge clk) begin")
    lines:add("        %scmd_reg <= %scmd_reg_pre;", prefix, prefix)
    lines:add("    end")
    lines:add("    always @(posedge clk) begin")
    lines:add("        if(%sreceive_command) begin", prefix)
    lines:add("            %scmd_reg_pre <= (%scmd_reg << 1) | data_in;", prefix, prefix)
    lines:add("        end")
    lines:add("        else begin")
    lines:add("            %scmd_reg_pre <= (%scmd_reg << 1);", prefix, prefix)
    lines:add("        end")
    lines:add("    end")
    lines:add("    always @(posedge clk) begin")
    lines:add("        if(reset_internal) begin")
    lines:add("            %sreset_flag_pre <= 1'b1;", prefix)
    lines:add("            %scurr_state_pre <= %scurr_state;", prefix, prefix)
    lines:add("        end")
    lines:add("        else begin")
    lines:add("            %sreset_flag_pre <= 1'b0;", prefix)
    lines:add("            if(%sreset_flag) begin", prefix)
    lines:add("                %scurr_state_pre <= RESET_REGISTER_ST;", prefix)
    lines:add("            end")
    lines:add("            else begin")
    lines:add("                case (%scurr_state)", prefix)
    lines:add("                    WAIT_FOR_COMMAND_ST : begin")
    lines:add("                        if(%scommand_ready) begin", prefix)
    lines:add("                            case (%scommand)", prefix)
    lines:add("                                %s: begin", util.format_binary(settings.commands.reset))
    lines:add("                                    %scurr_state_pre <= RESET_REGISTER_ST;", prefix)
    lines:add("                                end")
    if settings.commands.update then
        lines:add("                                %s: begin", util.format_binary(settings.commands.update))
        lines:add("                                    %scurr_state_pre <= UPDATE_ST;", prefix)
        lines:add("                                end")
    end
    lines:add("                                %s: begin", util.format_binary(settings.commands.send))
    lines:add("                                    %scurr_state_pre <= SEND_DATA_SETUP_ST;", prefix)
    lines:add("                                end")
    lines:add("                                %s: begin", util.format_binary(settings.commands.receive))
    lines:add("                                    %scurr_state_pre <= RECEIVE_DATA_ST;", prefix)
    lines:add("                                end")
    lines:add("                                default: begin")
    -- FIXME: error mode?
    lines:add("                                    %scurr_state_pre <= WAIT_FOR_COMMAND_ST;", prefix)
    lines:add("                                end")
    lines:add("                            endcase")
    lines:add("                        end")
    lines:add("                        else begin")
    lines:add("                            %scurr_state_pre <= WAIT_FOR_COMMAND_ST;", prefix)
    lines:add("                        end")
    lines:add("                    end")
    lines:add("                    UPDATE_ST: begin")
    lines:add("                        %scurr_state_pre <= FLUSH_COMMAND_ST;", prefix)
    lines:add("                    end")
    lines:add("                    RESET_REGISTER_ST: begin")
    lines:add("                        %scurr_state_pre <= FLUSH_COMMAND_ST;", prefix)
    lines:add("                    end")
    lines:add("                    SEND_DATA_SETUP_ST: begin")
    lines:add("                        %scurr_state_pre <= SEND_DATA_ST;", prefix)
    lines:add("                    end")
    lines:add("                    SEND_DATA_ST: begin")
    lines:add("                        if (data_ready) begin")
    lines:add("                            %scurr_state_pre <= SEND_DATA_RECOVER_ST;", prefix)
    lines:add("                        end")
    lines:add("                        else begin")
    lines:add("                            %scurr_state_pre <= SEND_DATA_ST;", prefix)
    lines:add("                        end")
    lines:add("                    end")
    lines:add("                    SEND_DATA_RECOVER_ST : begin")
    lines:add("                        %scurr_state_pre <= FLUSH_COMMAND_ST;", prefix)
    lines:add("                    end")
    lines:add("                    RECEIVE_DATA_ST: begin")
    lines:add("                        if (data_ready) begin")
    if settings.commands.update then
        lines:add("                            %scurr_state_pre <= FLUSH_COMMAND_ST;", prefix)
    else
        lines:add("                            %scurr_state_pre <= UPDATE_ST;", prefix)
    end
    lines:add("                        end")
    lines:add("                        else begin")
    lines:add("                            %scurr_state_pre <= RECEIVE_DATA_ST;", prefix)
    lines:add("                        end")
    lines:add("                    end")
    lines:add("                    FLUSH_COMMAND_ST: begin")
    lines:add("                        if(%scommand_empty) begin", prefix)
    lines:add("                            %scurr_state_pre <= WAIT_FOR_COMMAND_ST;", prefix)
    lines:add("                        end")
    lines:add("                        else begin")
    lines:add("                            %scurr_state_pre <= FLUSH_COMMAND_ST;", prefix)
    lines:add("                        end")
    lines:add("                    end")
    lines:add("                endcase")
    lines:add("            end")
    lines:add("        end")
    lines:add("    end")
    lines:add("    always @(negedge clk) begin")
    lines:add("        %scurr_state <= %scurr_state_pre;", prefix, prefix)
    lines:add("        %sreset_flag <= %sreset_flag_pre;", prefix, prefix)
    lines:add("    end")
    if not flat then
        lines:add("endmodule")
    end
    return lines
end

