local settings = require "settings"

local lines = {}

table.insert(lines, "//`define DEBUG_LEVEL")
table.insert(lines, "`define LOWER_LIMIT 0")
table.insert(lines, string.format("`define UPPER_LIMIT 2 ** %d - 1", settings.data_length))
table.insert(lines, "")
table.insert(lines, "`define IDLE_CYCLES 0")
table.insert(lines, "`define CYCLE_BREAK 0")
table.insert(lines, "")
table.insert(lines, "module testbench;")
table.insert(lines, "    // general settings")
table.insert(lines, "    //timeunit 1ns/1ps;")
table.insert(lines, "    initial begin")
table.insert(lines, "        // shall print %t with scaled in ns (-9), with 2 precision digits, and would print the \" ns\" string")
table.insert(lines, "        $timeformat(-9, 2, \" ns\", 20);")
table.insert(lines, "    end")
table.insert(lines, "")
table.insert(lines, "    reg clk = 0;")
table.insert(lines, "    always #5 clk = ~clk;")
table.insert(lines, "")
table.insert(lines, "    wire data_inout;")
table.insert(lines, string.format("    wire [0:%d] bit_out;", settings.data_length - 1))
table.insert(lines, "    reg write_not_read;")
table.insert(lines, "    reg data_in;")
table.insert(lines, string.format("    reg [0:%d] test_data;", settings.data_length - 1))
table.insert(lines, string.format("    reg [0:%d] test_data_out;", settings.data_length - 1))
table.insert(lines, "")
table.insert(lines, "    assign (supply0, supply1) data_inout = (write_not_read == 1'b1) ? data_in : 1'bZ;")
table.insert(lines, "    pulldown(data_inout);")
table.insert(lines, "")
table.insert(lines, "    // place serial interface DUT")
table.insert(lines, "    serial_interface serial_interface(")
table.insert(lines, "      .clk(clk),")
table.insert(lines, "      .data_inout(data_inout),")
table.insert(lines, "      .bit_out(bit_out)")
table.insert(lines, "    );")
table.insert(lines, "")
table.insert(lines, "    // task definitions ")
table.insert(lines, "    task wait_n_clk_cycles(int n_cycles);")
table.insert(lines, "        for (int i = 0; i < n_cycles; i++) begin")
table.insert(lines, "            @(negedge clk);")
table.insert(lines, "        end")
table.insert(lines, "        `ifdef DEBUG_LEVEL")
table.insert(lines, "            $display(\"time is %0t after waiting\", $time);")
table.insert(lines, "        `endif")
table.insert(lines, "    endtask")
table.insert(lines, "")
table.insert(lines, "    task send_stop_bit;")
table.insert(lines, "        data_in <= 1'b0;")
table.insert(lines, "        @(negedge clk);")
table.insert(lines, "    endtask")
table.insert(lines, "")
table.insert(lines, "    task send_command(reg [`CMD_LEN - 1:0] cmd);")
table.insert(lines, "        // send start bits")
table.insert(lines, "        data_in <= 1'b1;")
table.insert(lines, "        @(negedge clk);")
table.insert(lines, "        data_in <= 1'b0;")
table.insert(lines, "        @(negedge clk);")
table.insert(lines, "        data_in <= 1'b1;")
table.insert(lines, "")
table.insert(lines, "        // send command")
table.insert(lines, "        for(int i = `CMD_LEN - 1; i >= 0; i--) begin")
table.insert(lines, "            @(negedge clk);")
table.insert(lines, "            data_in <= cmd[i];")
table.insert(lines, "            `ifdef DEBUG_LEVEL")
table.insert(lines, "                $display(\"wrote command bit %b at %0t\", cmd[i], $time);")
table.insert(lines, "            `endif ")
table.insert(lines, "        end")
table.insert(lines, "        @(negedge clk);")
table.insert(lines, "")
table.insert(lines, "        `ifdef DEBUG_LEVEL")
table.insert(lines, "            $display(\"time is %0t after command\", $time);")
table.insert(lines, "        `endif ")
table.insert(lines, "    endtask")
table.insert(lines, "")
table.insert(lines, string.format("    task send_data(reg [%d:0] data);", settings.data_length - 1))
table.insert(lines, string.format("        for(int i = 0; i < %d; i++) begin", settings.data_length))
table.insert(lines, "            data_in <= data[i];")
table.insert(lines, "            @(negedge clk);")
table.insert(lines, "")
table.insert(lines, "            `ifdef DEBUG_LEVEL")
table.insert(lines, "                assert (serial_interface.curr_state == RCV_DATA_ST) else $error(\"error receive state at %0t\", $time);")
table.insert(lines, "                $display(\"wrote data bit %b at %0t\", data[i], $time);")
table.insert(lines, "            `endif")
table.insert(lines, "        end")
table.insert(lines, "        data_in = 0;")
table.insert(lines, "        `ifdef DEBUG_LEVEL")
table.insert(lines, "            $display(\"time is %0t after data\", $time);")
table.insert(lines, "        `endif")
table.insert(lines, "    endtask")
table.insert(lines, "")
table.insert(lines, "    // test procedure")
table.insert(lines, "    initial begin")
table.insert(lines, "        data_in <= 1'b0;")
table.insert(lines, "        write_not_read = 1'b1;    ")
table.insert(lines, "")
table.insert(lines, "        `ifdef DEBUG_LEVEL")
table.insert(lines, "            $monitor(\"data_in = %b\", data_in);")
table.insert(lines, "            $monitor(\"ser_ctrl_cmd_reg = %b\", serial_interface.cmd_reg);")
table.insert(lines, "        `endif")
table.insert(lines, "")
table.insert(lines, "        `ifdef DEBUG_LEVEL")
table.insert(lines, "            assert (serial_interface.curr_state == RESET_ST) else $error(\"error reset at %0t\", $time);")
table.insert(lines, "        `endif")
table.insert(lines, "")
table.insert(lines, "        // force reset of internal circuitry (NOT reset command, which resets the data registers)")
table.insert(lines, "        write_not_read = 1'b1; ")
table.insert(lines, "        data_in <= 1'b0;")
table.insert(lines, string.format("        wait_n_clk_cycles(%d);", settings.reset_numbits))
table.insert(lines, "        data_in <= 1'b1;")
table.insert(lines, string.format("        wait_n_clk_cycles(%d);", settings.reset_numbits))
table.insert(lines, "        data_in <= 1'b0;")
table.insert(lines, "")
table.insert(lines, "        // wait for reset")
table.insert(lines, "        wait_n_clk_cycles(10);")
table.insert(lines, "")
table.insert(lines, "        test_data = 0;")
table.insert(lines, "        assert (bit_out == test_data) else $error(\"bit out %b at %b\", bit_out, test_data);")
table.insert(lines, "")
table.insert(lines, "        // loop to try all possible values that can be stored in the daisychain")
table.insert(lines, "        for (int i = `LOWER_LIMIT; i <= `UPPER_LIMIT; i++) begin")
table.insert(lines, "            test_data = i;")
table.insert(lines, "")
table.insert(lines, "            send_command(`START_RECEIVE_CMD);")
table.insert(lines, "            send_stop_bit();")
table.insert(lines, "            send_data(test_data);")
table.insert(lines, "            wait_n_clk_cycles(`IDLE_CYCLES);")
table.insert(lines, "")
table.insert(lines, "            send_command(`UPDATE_CMD);")
table.insert(lines, "            send_stop_bit();")
table.insert(lines, "            wait_n_clk_cycles(`IDLE_CYCLES);")
table.insert(lines, "")
table.insert(lines, "            wait_n_clk_cycles(2); // wait until data is ready (takes two cycles after command)")
table.insert(lines, "            assert (bit_out == test_data) else $error(\"bit out %b at %b\", bit_out, test_data);")
table.insert(lines, "")
table.insert(lines, "            send_command(`START_SEND_CMD);")
table.insert(lines, "            send_stop_bit();")
table.insert(lines, "            write_not_read = 1'b0; ")
table.insert(lines, "            // receive data")
table.insert(lines, "            @(posedge clk); // skip acknowledge phase")
table.insert(lines, string.format("            for(int i = %d; i >= 0; i--) begin", settings.data_length - 1))
table.insert(lines, "                @(posedge clk);")
table.insert(lines, "                test_data_out[i] = data_inout; ")
table.insert(lines, "            end")
table.insert(lines, "            @(negedge clk);")
table.insert(lines, "            @(negedge clk); // FIXME: why twice?")
table.insert(lines, "            write_not_read = 1'b1;    ")
table.insert(lines, "            wait_n_clk_cycles(`IDLE_CYCLES);")
table.insert(lines, "")
table.insert(lines, "            assert (test_data == test_data_out) $display(\"OK %b\", test_data);")
table.insert(lines, "                  else $error(\"data read error! expected: %b, got: %b\", test_data, test_data_out);")
table.insert(lines, "")
table.insert(lines, "            wait_n_clk_cycles(`CYCLE_BREAK);")
table.insert(lines, "        end")
table.insert(lines, "")
table.insert(lines, "        wait_n_clk_cycles(10);")
table.insert(lines, "")
table.insert(lines, "        //// test reset")
table.insert(lines, "        //send_command(`RESET_CMD);")
table.insert(lines, "        //wait_n_clk_cycles(2); // wait for reset")
table.insert(lines, "        //wait_n_clk_cycles(`IDLE_CYCLES);")
table.insert(lines, "")
table.insert(lines, "        $finish;")
table.insert(lines, "    end")
table.insert(lines, "    initial begin")
table.insert(lines, "        $dumpfile(\"signals.vcd\");")
table.insert(lines, "        $dumpvars(0, testbench);")
table.insert(lines, "    end")
table.insert(lines, "endmodule")

local file = io.open("testbench.v", "w")
file:write(table.concat(lines, "\n"))
file:close()
