local util = require "util"

local settings = require "settings"

local lines = util.make_lines_insert()

-- toplevel module header
lines:add("module serial_interface")

-- toplevel ports
lines:add("(")
lines:add("    /* off-chip ports (but only data_inout and clk actually cross the chip boundary) */")
lines:add("    input wire clk,")
lines:add("    input wire data_in,")
lines:add("    output wire data_out,")
lines:add("    output wire write,")
lines:add("    /* on-chip ports */")
lines:add("    output reg [%d:0] bit_out", settings.data_length - 1)
lines:add(");")

-- internal wires
lines:add("    wire enable_data_counter;")
lines:add("    wire data_ready;")
lines:add("    wire reset_internal;")
lines:add("    wire update;")
lines:add("    wire reset_shift_register;")
lines:add("    wire enable_shift_register;")
lines:add("    wire data_out_shift_reg;")
lines:add("    wire write_shift_register;")
lines:add("    wire receive_command;")
lines:add("    wire command_ready;")
lines:add("    wire command_empty;")
lines:add("    wire [%d:0] command;", settings.commands_length - 1)

-- command register
lines:add("    // command register")
lines:add("    reg [%d:0] _command_register_cmd_reg;", settings.commands_length + settings.start_pattern_length - 1)
lines:add("    reg [%d:0] _command_register_cmd_reg_pre;", settings.commands_length + settings.start_pattern_length - 1)
lines:add( "    assign command_empty = _command_register_cmd_reg == 0;")
lines:add( "    assign command_ready =")
for i = 1, settings.start_pattern_length do
    local line = {}
    table.insert(line, string.format("        _command_register_cmd_reg[%d] == 1'b%d", settings.commands_length +  settings.start_pattern_length - i, settings.start_pattern[i]))
    if i ~= settings.start_pattern_length then
        table.insert(line, " &&")
    else
        table.insert(line, ";")
    end
    lines:add(table.concat(line))
end
lines:add("    assign command = _command_register_cmd_reg[%d:0];", settings.commands_length - 1)
lines:add("    always @ (negedge clk) begin")
lines:add("        _command_register_cmd_reg <= _command_register_cmd_reg_pre;")
lines:add("    end")
lines:add("    always @(posedge clk) begin")
lines:add("        if(receive_command) begin")
lines:add("            _command_register_cmd_reg_pre <= (_command_register_cmd_reg << 1) | data_in;")
lines:add("        end")
lines:add("        else begin")
lines:add("            _command_register_cmd_reg_pre <= (_command_register_cmd_reg << 1);")
lines:add("        end")
lines:add("    end")

-- control module
lines:add("    // control module")
lines:add("    // control part state machine")
lines:add("    // states are coded in order to minimize instance count")
lines:add("    localparam")
lines:add("        RESET_ST             = 4'b1xxx,  // reset control circuit")
lines:add("        RECEIVE_DATA_ST      = 4'b0010,  // receiving data")
lines:add("        SEND_DATA_ST         = 4'b0000,  // sending data")
lines:add("        WAIT_FOR_COMMAND_ST  = 4'b0100,  // wait for command")
lines:add("        SEND_DATA_SETUP_ST   = 4'b0110,  // sending data, setup tristate buffer")
lines:add("        UPDATE_ST            = 4'b0011,  // update shift register")
lines:add("        RESET_REGISTER_ST    = 4'b0111,  // reset shift register")
lines:add("        SEND_DATA_RECOVER_ST = 4'b0001,  // recover from write/read shift to prevent glitches")
lines:add("        FLUSH_COMMAND_ST     = 4'b0101;")
lines:add("")
lines:add("    reg [3:0] _control_curr_state_pre;  // changes with posedge")
lines:add("    reg [3:0] _control_curr_state;      // changes with negedge")
lines:add("")
lines:add("    // enable write")
lines:add("    assign write = (_control_curr_state == SEND_DATA_ST);")
lines:add("")
lines:add("    // enable writing to shift register")
lines:add("    assign write_shift_register = (_control_curr_state == RECEIVE_DATA_ST);")
lines:add("")
lines:add("    // enable shifting of shift register")
lines:add("    assign enable_shift_register = write || write_shift_register;")
lines:add("")
lines:add("    // reset shift register (synchronous reset, triggered by the update signal)")
lines:add("    assign reset_shift_register = !(_control_curr_state == RESET_REGISTER_ST);")
lines:add("")
lines:add("    // update shift register")
lines:add("    assign update_shift_register = (_control_curr_state == UPDATE_ST) || (_control_curr_state == RESET_REGISTER_ST);")
lines:add("")
lines:add("    // reset counter")
lines:add("    assign enable_data_counter = (_control_curr_state == RECEIVE_DATA_ST) || (_control_curr_state == SEND_DATA_ST);")
lines:add("")
lines:add("    // receive command")
lines:add("    assign receive_command = _control_curr_state == WAIT_FOR_COMMAND_ST;")
lines:add("")
lines:add("    always @(posedge clk) begin")
lines:add("        if(reset_internal) begin")
lines:add("            _control_curr_state_pre <= RESET_ST;")
lines:add("        end")
lines:add("        else begin")
lines:add("            case (_control_curr_state)")
lines:add("                RESET_ST : begin")
lines:add("                    _control_curr_state_pre <= RESET_REGISTER_ST;")
lines:add("                end")
lines:add("                WAIT_FOR_COMMAND_ST : begin")
lines:add("                    if(command_ready) begin")
lines:add("                        case (command)")
lines:add("                            %s: begin", util.format_binary(settings.commands.reset))
lines:add("                                _control_curr_state_pre <= RESET_REGISTER_ST;")
lines:add("                            end")
if settings.commands.update then
    lines:add("                            %s: begin", util.format_binary(settings.commands.update))
    lines:add("                                _control_curr_state_pre <= UPDATE_ST;")
    lines:add("                            end")
end
lines:add("                            %s: begin", util.format_binary(settings.commands.send))
lines:add("                                _control_curr_state_pre <= SEND_DATA_SETUP_ST;")
lines:add("                            end")
lines:add("                            %s: begin", util.format_binary(settings.commands.receive))
lines:add("                                _control_curr_state_pre <= RECEIVE_DATA_ST;")
lines:add("                            end")
lines:add("                            default: begin")
-- FIXME: error mode?
lines:add("                                _control_curr_state_pre <= WAIT_FOR_COMMAND_ST;")
lines:add("                            end")
lines:add("                        endcase")
lines:add("                    end")
lines:add("                    else begin")
lines:add("                        _control_curr_state_pre <= WAIT_FOR_COMMAND_ST;")
lines:add("                    end")
lines:add("                end")
lines:add("                UPDATE_ST: begin")
lines:add("                    _control_curr_state_pre <= FLUSH_COMMAND_ST;")
lines:add("                end")
lines:add("                RESET_REGISTER_ST: begin")
lines:add("                    _control_curr_state_pre <= FLUSH_COMMAND_ST;")
lines:add("                end")
lines:add("                SEND_DATA_SETUP_ST: begin")
lines:add("                    _control_curr_state_pre <= SEND_DATA_ST;")
lines:add("                end")
lines:add("                SEND_DATA_ST: begin")
lines:add("                    if (data_ready) begin")
lines:add("                        _control_curr_state_pre <= SEND_DATA_RECOVER_ST;")
lines:add("                    end")
lines:add("                    else begin")
lines:add("                        _control_curr_state_pre <= SEND_DATA_ST;")
lines:add("                    end")
lines:add("                end")
lines:add("                SEND_DATA_RECOVER_ST : begin")
lines:add("                    _control_curr_state_pre <= FLUSH_COMMAND_ST;")
lines:add("                end")
lines:add("                RECEIVE_DATA_ST: begin")
lines:add("                    if (data_ready) begin")
if settings.commands.update then
    lines:add("                        _control_curr_state_pre <= FLUSH_COMMAND_ST;")
else
    lines:add("                        _control_curr_state_pre <= UPDATE_ST;")
end
lines:add("                    end")
lines:add("                    else begin")
lines:add("                        _control_curr_state_pre <= RECEIVE_DATA_ST;")
lines:add("                    end")
lines:add("                end")
lines:add("                FLUSH_COMMAND_ST: begin")
lines:add("                    if(command_empty) begin")
lines:add("                        _control_curr_state_pre <= WAIT_FOR_COMMAND_ST;")
lines:add("                    end")
lines:add("                    else begin")
lines:add("                        _control_curr_state_pre <= FLUSH_COMMAND_ST;")
lines:add("                    end")
lines:add("                end")
lines:add("            endcase")
lines:add("        end")
lines:add("    end")
lines:add("    always @(negedge clk) begin")
lines:add("        _control_curr_state <= _control_curr_state_pre;")
lines:add("    end")
lines:add("")

-- reset counter
lines:add("    // reset counter")
lines:add("    reg [%d:0] _reset_counter_outp;", settings.reset_length - 1)
lines:add("    reg [%d:0] _reset_counter_outn;", settings.reset_length - 1)
lines:add("    assign reset_internal = !_reset_counter_outn[%d];", settings.reset_length - 1)
lines:add("    always @(posedge clk) begin")
lines:add("        if(data_in) begin")
lines:add("            _reset_counter_outp <= _reset_counter_outn - 1;")
lines:add("        end")
lines:add("        else begin")
lines:add("            _reset_counter_outp <= %s;", util.format_binary(util.fill_length_with(settings.reset_length, 1)))
lines:add("        end")
lines:add("    end")
lines:add("    always @(negedge clk) begin")
lines:add("        _reset_counter_outn <= _reset_counter_outp;")
lines:add("    end")
lines:add("")

-- data counter
lines:add("    // data counter")
lines:add("    reg [%d:0] _data_counter_outp;", settings.data_numbits - 1)
lines:add("    reg [%d:0] _data_counter_outn;", settings.data_numbits - 1)
lines:add("    assign data_ready = (_data_counter_outn == 2 ** %d - %d);", settings.data_numbits, settings.data_length)
lines:add("    always @(posedge clk) begin")
lines:add("        if(enable_data_counter) begin")
lines:add("            _data_counter_outp <= _data_counter_outn - 1;")
lines:add("        end")
lines:add("        else begin")
lines:add("            _data_counter_outp <= %s;", util.format_binary(util.fill_length_with(settings.data_numbits, 1)))
lines:add("        end")
lines:add("    end")
lines:add("    always @(negedge clk) begin")
lines:add("        _data_counter_outn <= _data_counter_outp;")
lines:add("    end")
lines:add("")

-- shift register
lines:add("    // shift register")
lines:add("    reg [%d:0] _shift_register_ff_in;", settings.data_length - 1)
lines:add("    reg [%d:0] _shift_register_cells_out;", settings.data_length - 1)
lines:add("    reg [%d:0] _shift_register_store;", settings.data_length - 1)
lines:add("    assign data_out = _shift_register_cells_out[0];")
-- flip-flop chain-in
lines:add("    always @(posedge clk) begin")
lines:add("        if (enable_shift_register) begin")
lines:add("            if (write_shift_register) begin")
lines:add("                _shift_register_ff_in[%d:0] <= { data_in, _shift_register_cells_out[%d:1] };", settings.data_length - 1, settings.data_length - 1)
lines:add("            end")
lines:add("            else begin")
lines:add("                _shift_register_ff_in[%d:0] <= { _shift_register_cells_out[0], _shift_register_cells_out[%d:1] };", settings.data_length - 1, settings.data_length - 1)
lines:add("            end")
lines:add("        end")
lines:add("        else begin")
lines:add("            _shift_register_ff_in[%d:0] <= _shift_register_cells_out[%d:0];", settings.data_length - 1, settings.data_length - 1)
lines:add("        end")
lines:add("    end")

-- flip-flop chain-out
lines:add("    always @(negedge clk) begin")
lines:add("        _shift_register_cells_out[%d:0] <= _shift_register_ff_in[%d:0];", settings.data_length - 1, settings.data_length - 1)
lines:add("    end")
-- flip-flop bit datum
local resetpattern_formatted = {}
for i = settings.data_length - 1, 0, -1 do
    table.insert(resetpattern_formatted, settings.resetpattern[settings.data_length - i] == 1 and "1" or "0")
end
lines:add("    always @(posedge clk) begin")
lines:add("        if (!reset_shift_register) begin")
lines:add("            bit_out[%d:0] <= %d'b%s;", settings.data_length - 1, settings.data_length, table.concat(resetpattern_formatted))
lines:add("        end")
lines:add("        else begin")
lines:add("            if(update_shift_register) begin")
lines:add("                bit_out[%d:0] <= _shift_register_cells_out[%d:0];", settings.data_length - 1, settings.data_length - 1)
lines:add("            end")
lines:add("            else begin")
lines:add("                bit_out[%d:0] <= _shift_register_store[%d:0];", settings.data_length - 1, settings.data_length - 1)
lines:add("            end")
lines:add("        end")
lines:add("    end")
-- flip-flop bit store
lines:add("    always @(negedge clk) begin")
lines:add("        _shift_register_store[%d:0] <= bit_out[%d:0];", settings.data_length - 1, settings.data_length - 1)
lines:add("    end")

-- finished toplevel module
lines:add("endmodule")

local file = io.open("serial_interface.v", "w")
file:write(table.concat(lines, "\n"))
file:close()
