local settings = require "settings"

local lines = {}

table.insert(lines, "module serial_interface")
table.insert(lines, "(")
table.insert(lines, "    /* off-chip ports (but only data_inout and clk actually cross the chip boundary) */")
table.insert(lines, "    input wire clk,")
table.insert(lines, "    input wire data_in,")
table.insert(lines, "    output wire data_out,")
table.insert(lines, "    output wire write,")
table.insert(lines, "    /* on-chip ports */")
table.insert(lines, string.format("    output wire [%d:0] bit_out", settings.data_length - 1))
table.insert(lines, ");")
table.insert(lines, "    wire enable_data_counter;")
table.insert(lines, "    wire data_ready;")
table.insert(lines, "    wire reset_internal;")
table.insert(lines, "")
table.insert(lines, "    wire update;")
table.insert(lines, "    wire reset_shift_register;")
table.insert(lines, "    wire enable_shift_register;")
table.insert(lines, "    wire data_out_shift_reg;")
table.insert(lines, "    wire write_shift_register;")
table.insert(lines, "")
table.insert(lines, "    serial_ctrl control (")
table.insert(lines, "        .clk(clk),")
table.insert(lines, "        .data_in(data_in),")
table.insert(lines, "        .write(write),")
table.insert(lines, "        .data_ready(data_ready),")
table.insert(lines, "        .reset_internal(reset_internal),")
table.insert(lines, "        .enable_data_counter(enable_data_counter),")
table.insert(lines, "        .update(update),")
table.insert(lines, "        .reset_shift_reg_out(reset_shift_register),")
table.insert(lines, "        .enable_shift_register(enable_shift_register),")
table.insert(lines, "        .write_shift_register(write_shift_register)")
table.insert(lines, "    );")
table.insert(lines, "")
table.insert(lines, "    reset_counter reset_counter (")
table.insert(lines, "        .clk(clk),")
table.insert(lines, "        .data(data_in),")
table.insert(lines, "        .reset(reset_internal)")
table.insert(lines, "    );")
table.insert(lines, "")
table.insert(lines, "    data_counter data_counter (")
table.insert(lines, "        .clk(clk),")
table.insert(lines, "        .reset(enable_data_counter),")
table.insert(lines, "        .data_ready(data_ready)")
table.insert(lines, "    );")
table.insert(lines, "")
table.insert(lines, "    shift_register daisychain (")
table.insert(lines, "        .clk(clk),")
table.insert(lines, "        .data_in(data_in),")
table.insert(lines, "        .update(update),")
table.insert(lines, "        .reset(reset_shift_register),")
table.insert(lines, "        .enable(enable_shift_register),")
table.insert(lines, "        .write(write_shift_register),")
table.insert(lines, "        .data_out(data_out),")
table.insert(lines, "        .bit_out(bit_out)")
table.insert(lines, "    );")
table.insert(lines, "endmodule")

local file = io.open("serial_interface.v", "w")
file:write(table.concat(lines, "\n"))
file:close()
