local settings = require "settings"

local util = require "util"

local lines = util.make_lines_insert()

lines:add("module serial_ctrl")
lines:add("(")
lines:add("    input clk,")
lines:add("    input data_in,")
lines:add("    output wire write,")
lines:add("    input data_ready,")
lines:add("    input data_out_shift_reg_in,")
lines:add("    input reset_internal,")
lines:add("    output enable_data_counter,")
lines:add("    output wire update,")
lines:add("    output wire reset_shift_reg_out,")
lines:add("    output wire enable_shift_register,")
lines:add("    output wire write_shift_register")
lines:add(");")
lines:add("    // control part state machine")
lines:add("    // states are coded in order to minimize instance count")
lines:add("    localparam ")
lines:add("        RESET_ST             = 4'b1xxx,  // reset control circuit")
lines:add("        RECEIVE_DATA_ST      = 4'b0010,  // receiving data")
lines:add("        SEND_DATA_ST         = 4'b0000,  // sending data")
lines:add("        WAIT_FOR_COMMAND_ST  = 4'b0100,  // wait for command")
lines:add("        SEND_DATA_SETUP_ST   = 4'b0110,  // sending data, setup tristate buffer")
lines:add("        UPDATE_ST            = 4'b0011,  // update shift register")
lines:add("        RESET_REGISTER_ST    = 4'b0111,  // reset shift register")
lines:add("        SEND_DATA_RECOVER_ST = 4'b0001,  // recover from write/read shift to prevent glitches")
lines:add("        FLUSH_COMMAND_ST     = 4'b0101;")
lines:add("")
lines:add("    reg [3:0] curr_state_pre;  // changes with posedge")
lines:add("    reg [3:0] curr_state;      // changes with negedge")
lines:add("")
lines:add("    assign write = (curr_state == SEND_DATA_ST);")
lines:add("")
lines:add("    assign write_shift_register = (curr_state == RECEIVE_DATA_ST);")
lines:add("")
lines:add("    assign enable_shift_register = write || write_shift_register;")
lines:add("")
lines:add("    // reset shift register (synchronous reset, triggered by the update signal)")
lines:add("    assign reset_shift_reg_out = !(curr_state == RESET_REGISTER_ST);")
lines:add("")
lines:add("    // update shift register")
lines:add("    assign update = (curr_state == UPDATE_ST) || (curr_state == RESET_REGISTER_ST);")
lines:add("")
lines:add("    // reset counter")
lines:add("    assign enable_data_counter = (curr_state == RECEIVE_DATA_ST) || (curr_state == SEND_DATA_ST);")
lines:add("")
lines:add("    // command register")
lines:add("    wire receive_command;")
lines:add("    assign receive_command = curr_state == WAIT_FOR_COMMAND_ST;")
lines:add("    wire command_ready;")
lines:add("    wire command_empty;")
lines:add("    wire [%d:0] command;", settings.commands_length - 1)
lines:add("    command_register command_register(")
lines:add("        .clk(clk),")
lines:add("        .data(data_in),")
lines:add("        .receive(receive_command),")
lines:add("        .empty(command_empty),")
lines:add("        .ready(command_ready),")
lines:add("        .command(command)")
lines:add("    );")
lines:add("")
lines:add("    always @(posedge clk) begin")
lines:add("        if(reset_internal) begin")
lines:add("            curr_state_pre <= RESET_ST;")
lines:add("        end")
lines:add("        else begin")
lines:add("            case (curr_state)")
lines:add("                RESET_ST : begin")
lines:add("                    curr_state_pre <= RESET_REGISTER_ST;")
lines:add("                end")
lines:add("                WAIT_FOR_COMMAND_ST : begin")
lines:add("                    if(command_ready) begin")
lines:add("                        case (command)")
lines:add("                            %s: begin", util.format_binary(settings.commands.reset))
lines:add("                                curr_state_pre <= RESET_REGISTER_ST;")
lines:add("                            end")
if settings.commands.update then
    lines:add("                            %s: begin", util.format_binary(settings.commands.update))
    lines:add("                                curr_state_pre <= UPDATE_ST;")
    lines:add("                            end")
end
lines:add("                            %s: begin", util.format_binary(settings.commands.send))
lines:add("                                curr_state_pre <= SEND_DATA_SETUP_ST;")
lines:add("                            end")
lines:add("                            %s: begin", util.format_binary(settings.commands.receive))
lines:add("                                curr_state_pre <= RECEIVE_DATA_ST;")
lines:add("                            end")
lines:add("                            default: begin")
-- FIXME: error mode?
lines:add("                                curr_state_pre <= WAIT_FOR_COMMAND_ST;")
lines:add("                            end")
lines:add("                        endcase")
lines:add("                    end")
lines:add("                    else begin")
lines:add("                        curr_state_pre <= WAIT_FOR_COMMAND_ST;")
lines:add("                    end")
lines:add("                end")
lines:add("                UPDATE_ST: begin")
lines:add("                    curr_state_pre <= FLUSH_COMMAND_ST;")
lines:add("                end")
lines:add("                RESET_REGISTER_ST: begin")
lines:add("                    curr_state_pre <= FLUSH_COMMAND_ST;")
lines:add("                end")
lines:add("                SEND_DATA_SETUP_ST: begin")
lines:add("                    curr_state_pre <= SEND_DATA_ST;")
lines:add("                end")
lines:add("                SEND_DATA_ST: begin")
lines:add("                    if (data_ready) begin")
lines:add("                        curr_state_pre <= SEND_DATA_RECOVER_ST;")
lines:add("                    end")
lines:add("                    else begin")
lines:add("                        curr_state_pre <= SEND_DATA_ST;")
lines:add("                    end")
lines:add("                end")
lines:add("                SEND_DATA_RECOVER_ST : begin")
lines:add("                    curr_state_pre <= FLUSH_COMMAND_ST;")
lines:add("                end")
lines:add("                RECEIVE_DATA_ST: begin")
lines:add("                    if (data_ready) begin")
if settings.commands.update then
    lines:add("                        curr_state_pre <= FLUSH_COMMAND_ST;")
else
    lines:add("                        curr_state_pre <= UPDATE_ST;")
end
lines:add("                    end")
lines:add("                    else begin")
lines:add("                        curr_state_pre <= RECEIVE_DATA_ST;")
lines:add("                    end")
lines:add("                end")
lines:add("                FLUSH_COMMAND_ST: begin")
lines:add("                    if(command_empty) begin")
lines:add("                        curr_state_pre <= WAIT_FOR_COMMAND_ST;")
lines:add("                    end")
lines:add("                    else begin")
lines:add("                        curr_state_pre <= FLUSH_COMMAND_ST;")
lines:add("                    end")
lines:add("                end")
lines:add("            endcase")
lines:add("        end")
lines:add("    end")
lines:add("    always @(negedge clk) begin")
lines:add("        curr_state <= curr_state_pre;")
lines:add("    end")
lines:add("endmodule")

util.write_lines("control.v", lines)
