local settings = require "settings"

local util = require "util"

local lines = util.make_lines_insert()

lines:add("//`define DEBUG_LEVEL")
lines:add("`define LOWER_LIMIT 0")
lines:add("`define UPPER_LIMIT 2 ** %d - 1", settings.data_length)
lines:add("")
lines:add("`define IDLE_CYCLES %d", settings.idle_cycles)
lines:add("`define CYCLE_BREAK 0")
lines:add("")
lines:add("module testbench;")
lines:add("    // general settings")
lines:add("    //timeunit 1ns/1ps;")
lines:add("    initial begin")
lines:add("        // shall print %%t with scaled in ns (-9), with 2 precision digits, and would print the \" ns\" string")
lines:add("        $timeformat(-9, 2, \" ns\", 20);")
lines:add("    end")
lines:add("")
lines:add("    reg clk = 0;")
lines:add("    always #5 clk = ~clk;")
lines:add("")
lines:add("    wire data_inout;")
lines:add("    wire [0:%d] bit_out;", settings.data_length - 1)
lines:add("    reg write_not_read;")
lines:add("    reg data_in;")
lines:add("    reg [0:%d] test_data;", settings.data_length - 1)
lines:add("    reg [0:%d] test_data_out;", settings.data_length - 1)
lines:add("")
lines:add("    assign (supply0, supply1) data_inout = (write_not_read == 1'b1) ? data_in : 1'bZ;")
lines:add("    pulldown(data_inout);")
lines:add("")
lines:add("    // place serial interface DUT")
lines:add("    serial_interface serial_interface(")
lines:add("      .clk(clk),")
lines:add("      .data_inout(data_inout),")
lines:add("      .bit_out(bit_out)")
lines:add("    );")
lines:add("")
lines:add("    // task definitions ")
lines:add("    task wait_n_clk_cycles(int n_cycles);")
lines:add("        for (int i = 0; i < n_cycles; i++) begin")
lines:add("            @(negedge clk);")
lines:add("        end")
lines:add("        `ifdef DEBUG_LEVEL")
lines:add("            $display(\"time is %%0t after waiting\", $time);")
lines:add("        `endif")
lines:add("    endtask")
lines:add("")
lines:add("    task send_command(reg [%d:0] cmd);", settings.commands_length - 1)
lines:add("        // send start bits")
for i = 1, settings.start_pattern_length do
    lines:add("        data_in <= 1'b%d;", settings.start_pattern[i])
    if i ~= settings.start_pattern_length then
        lines:add("        @(negedge clk);")
    end
end
lines:add("")
lines:add("        // send command")
lines:add("        for(int i = %d; i >= 0; i--) begin", settings.commands_length - 1)
lines:add("            @(negedge clk);")
lines:add("            data_in <= cmd[i];")
lines:add("            `ifdef DEBUG_LEVEL")
lines:add("                $display(\"wrote command bit %%b at %%0t\", cmd[i], $time);")
lines:add("            `endif ")
lines:add("        end")
lines:add("        @(negedge clk);")
lines:add("")
lines:add("        `ifdef DEBUG_LEVEL")
lines:add("            $display(\"time is %%0t after command\", $time);")
lines:add("        `endif ")
lines:add("        // send stop bit")
lines:add("        data_in <= 1'b0;")
lines:add("        @(negedge clk);")
lines:add("    endtask")
lines:add("")
lines:add("    task send_data(reg [%d:0] data);", settings.data_length - 1)
lines:add("        for(int i = 0; i < %d; i++) begin", settings.data_length)
lines:add("            data_in <= data[i];")
lines:add("            @(negedge clk);")
lines:add("")
lines:add("            `ifdef DEBUG_LEVEL")
lines:add("                assert (serial_interface.curr_state == RCV_DATA_ST) else $error(\"error receive state at %%0t\", $time);")
lines:add("                $display(\"wrote data bit %%b at %%0t\", data[i], $time);")
lines:add("            `endif")
lines:add("        end")
lines:add("        data_in = 0;")
lines:add("        `ifdef DEBUG_LEVEL")
lines:add("            $display(\"time is %%0t after data\", $time);")
lines:add("        `endif")
lines:add("    endtask")
lines:add("")
lines:add("    // test procedure")
lines:add("    initial begin")
lines:add("        data_in <= 1'b0;")
lines:add("        write_not_read = 1'b1;    ")
lines:add("")
lines:add("        `ifdef DEBUG_LEVEL")
lines:add("            $monitor(\"data_in = %%b\", data_in);")
lines:add("            $monitor(\"ser_ctrl_cmd_reg = %%b\", serial_interface.cmd_reg);")
lines:add("        `endif")
lines:add("")
lines:add("        `ifdef DEBUG_LEVEL")
lines:add("            assert (serial_interface.curr_state == RESET_ST) else $error(\"error reset at %%0t\", $time);")
lines:add("        `endif")
lines:add("")
lines:add("        // force reset of internal circuitry (NOT reset command, which resets the data registers)")
lines:add("        write_not_read = 1'b1; ")
lines:add("        data_in <= 1'b0;")
lines:add("        wait_n_clk_cycles(%d);", settings.reset_numbits)
lines:add("        data_in <= 1'b1;")
lines:add("        wait_n_clk_cycles(%d);", settings.reset_numbits)
lines:add("        data_in <= 1'b0;")
lines:add("")
lines:add("        // wait for reset")
lines:add("        wait_n_clk_cycles(10);")
lines:add("")
lines:add("        test_data = 0;")
lines:add("        assert (bit_out == test_data) else $error(\"bit out %%b at %%b\", bit_out, test_data);")
lines:add("")
lines:add("        // loop to try all possible values that can be stored in the daisychain")
lines:add("        for (int i = `LOWER_LIMIT; i <= `UPPER_LIMIT; i++) begin")
lines:add("            test_data = i;")
lines:add("")
lines:add("            send_command(%s); // receive", util.format_binary(settings.commands.receive))
lines:add("            send_data(test_data);")
lines:add("            wait_n_clk_cycles(`IDLE_CYCLES);")
if settings.commands.update then
    lines:add("")
    lines:add("            send_command(%s); // update", util.format_binary(settings.commands.update))
    lines:add("            wait_n_clk_cycles(`IDLE_CYCLES);")
end
lines:add("")
lines:add("            wait_n_clk_cycles(2); // wait until data is ready (takes two cycles after command)")
lines:add("            assert (bit_out == test_data) else $error(\"bit out %%b at %%b\", bit_out, test_data);")
lines:add("")
lines:add("            send_command(%s); // send", util.format_binary(settings.commands.send))
lines:add("            write_not_read = 1'b0; ")
lines:add("            // receive data")
lines:add("            @(posedge clk); // skip acknowledge phase")
lines:add("            for(int i = %d; i >= 0; i--) begin", settings.data_length - 1)
lines:add("                @(posedge clk);")
lines:add("                test_data_out[i] = data_inout; ")
lines:add("            end")
lines:add("            @(negedge clk);")
lines:add("            @(negedge clk); // FIXME: why twice?")
lines:add("            write_not_read = 1'b1;    ")
lines:add("            wait_n_clk_cycles(`IDLE_CYCLES);")
lines:add("")
lines:add("            assert (test_data == test_data_out) $display(\"OK %%b\", test_data);")
lines:add("                  else $error(\"data read error! expected: %%b, got: %%b\", test_data, test_data_out);")
lines:add("")
lines:add("            wait_n_clk_cycles(`CYCLE_BREAK);")
lines:add("        end")
lines:add("")
lines:add("        wait_n_clk_cycles(10);")
lines:add("")
lines:add("        //// test reset")
lines:add("        //send_command(%s); // reset ", util.format_binary(settings.commands.reset))
lines:add("        //wait_n_clk_cycles(2); // wait for reset")
lines:add("        //wait_n_clk_cycles(`IDLE_CYCLES);")
lines:add("")
lines:add("        $finish;")
lines:add("    end")
lines:add("    initial begin")
lines:add("        $dumpfile(\"signals.vcd\");")
lines:add("        $dumpvars(0, testbench);")
lines:add("    end")
lines:add("endmodule")

util.write_lines("testbench.v", lines)
