/* Generated by Yosys 0.12 (git sha1 UNKNOWN, gcc 12.1.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fPIC -Os) */

(* src = "bit_counter.v:1.1-30.10" *)
module bit_counter(clk, reset_in, count_reached_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  (* src = "bit_counter.v:3.11-3.14" *)
  input clk;
  (* src = "bit_counter.v:11.27-11.32" *)
  wire [3:0] count;
  (* src = "bit_counter.v:12.27-12.36" *)
  wire [3:0] count_pre;
  (* src = "bit_counter.v:5.12-5.29" *)
  output count_reached_out;
  (* src = "bit_counter.v:4.11-4.19" *)
  input reset_in;
  not_gate _14_ (
    .I(count_pre[2]),
    .O(_04_)
  );
  nor_gate _15_ (
    .A(count_pre[1]),
    .B(count_pre[0]),
    .O(_05_)
  );
  and_gate _16_ (
    .A(_04_),
    .B(count_pre[3]),
    .O(_06_)
  );
  and_gate _17_ (
    .A(_05_),
    .B(_06_),
    .O(count_reached_out)
  );
  nand_gate _18_ (
    .A(count[0]),
    .B(reset_in),
    .O(_00_)
  );
  or_gate _19_ (
    .A(count[0]),
    .B(count[1]),
    .O(_07_)
  );
  nand_gate _20_ (
    .A(count[0]),
    .B(count[1]),
    .O(_08_)
  );
  and_gate _21_ (
    .A(reset_in),
    .B(_08_),
    .O(_09_)
  );
  nand_gate _22_ (
    .A(_07_),
    .B(_09_),
    .O(_01_)
  );
  or_gate _23_ (
    .A(count[2]),
    .B(_07_),
    .O(_10_)
  );
  nand_gate _24_ (
    .A(count[2]),
    .B(_07_),
    .O(_11_)
  );
  and_gate _25_ (
    .A(reset_in),
    .B(_11_),
    .O(_12_)
  );
  nand_gate _26_ (
    .A(_10_),
    .B(_12_),
    .O(_02_)
  );
  xor_gate _27_ (
    .A(count[3]),
    .B(_10_),
    .O(_13_)
  );
  nand_gate _28_ (
    .A(reset_in),
    .B(_13_),
    .O(_03_)
  );
  (* src = "bit_counter.v:17.1-24.4" *)
  dffnq _29_ (
    .CLK(clk),
    .D(_00_),
    .Q(count_pre[0])
  );
  (* src = "bit_counter.v:17.1-24.4" *)
  dffnq _30_ (
    .CLK(clk),
    .D(_01_),
    .Q(count_pre[1])
  );
  (* src = "bit_counter.v:17.1-24.4" *)
  dffnq _31_ (
    .CLK(clk),
    .D(_02_),
    .Q(count_pre[2])
  );
  (* src = "bit_counter.v:17.1-24.4" *)
  dffnq _32_ (
    .CLK(clk),
    .D(_03_),
    .Q(count_pre[3])
  );
  (* src = "bit_counter.v:26.1-28.4" *)
  dffpq _33_ (
    .CLK(clk),
    .D(count_pre[0]),
    .Q(count[0])
  );
  (* src = "bit_counter.v:26.1-28.4" *)
  dffpq _34_ (
    .CLK(clk),
    .D(count_pre[1]),
    .Q(count[1])
  );
  (* src = "bit_counter.v:26.1-28.4" *)
  dffpq _35_ (
    .CLK(clk),
    .D(count_pre[2]),
    .Q(count[2])
  );
  (* src = "bit_counter.v:26.1-28.4" *)
  dffpq _36_ (
    .CLK(clk),
    .D(count_pre[3]),
    .Q(count[3])
  );
endmodule

(* src = "register_cell.v:2.1-45.10" *)
module register_cell(chain_in, update, clk, reset, enable, chain_out, bit_out);
  (* src = "register_cell.v:22.5-29.8" *)
  wire _0_;
  wire _1_;
  (* src = "register_cell.v:10.10-10.17" *)
  output bit_out;
  (* src = "register_cell.v:4.9-4.17" *)
  input chain_in;
  (* src = "register_cell.v:9.10-9.19" *)
  output chain_out;
  (* src = "register_cell.v:6.9-6.12" *)
  input clk;
  (* src = "register_cell.v:8.9-8.15" *)
  input enable;
  (* src = "register_cell.v:21.9-21.14" *)
  wire ff_in;
  (* src = "register_cell.v:7.9-7.14" *)
  input reset;
  (* src = "register_cell.v:5.9-5.15" *)
  input update;
  mux _2_ (
    .A(chain_in),
    .B(chain_out),
    .O(_0_),
    .SEL(enable)
  );
  and_gate _3_ (
    .A(ff_in),
    .B(reset),
    .O(_1_)
  );
  (* src = "register_cell.v:37.5-44.8" *)
  dffpq _4_ (
    .CLK(update),
    .D(_1_),
    .Q(bit_out)
  );
  (* src = "register_cell.v:32.5-34.8" *)
  dffnq _5_ (
    .CLK(clk),
    .D(ff_in),
    .Q(chain_out)
  );
  (* src = "register_cell.v:22.5-29.8" *)
  dffpq _6_ (
    .CLK(clk),
    .D(_0_),
    .Q(ff_in)
  );
endmodule

(* src = "serial_ctrl.v:1.1-171.10" *)
module serial_ctrl(clk, data_in, write, count_reached_in, data_out_shift_reg_in, reset_count_out, update, reset_shift_reg_out, enable_shift_register, write_shift_register);
  (* src = "serial_ctrl.v:74.5-81.8" *)
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  (* src = "serial_ctrl.v:3.11-3.14" *)
  input clk;
  (* src = "serial_ctrl.v:87.27-87.34" *)
  wire [4:0] cmd_reg;
  (* src = "serial_ctrl.v:88.27-88.38" *)
  wire [4:0] cmd_reg_pre;
  (* src = "serial_ctrl.v:6.11-6.27" *)
  input count_reached_in;
  (* src = "serial_ctrl.v:59.15-59.25" *)
  wire [3:0] curr_state;
  (* src = "serial_ctrl.v:60.15-60.30" *)
  wire [3:0] curr_state_post;
  (* src = "serial_ctrl.v:58.15-58.29" *)
  wire [3:0] curr_state_pre;
  (* src = "serial_ctrl.v:4.11-4.18" *)
  input data_in;
  (* src = "serial_ctrl.v:7.11-7.32" *)
  input data_out_shift_reg_in;
  (* src = "serial_ctrl.v:11.12-11.33" *)
  output enable_shift_register;
  (* src = "serial_ctrl.v:8.12-8.27" *)
  output reset_count_out;
  (* src = "serial_ctrl.v:10.12-10.31" *)
  output reset_shift_reg_out;
  (* src = "serial_ctrl.v:26.27-26.34" *)
  wire [4:0] rst_reg;
  (* src = "serial_ctrl.v:26.36-26.47" *)
  wire [4:0] rst_reg_pre;
  (* src = "serial_ctrl.v:9.12-9.18" *)
  output update;
  (* src = "serial_ctrl.v:5.12-5.17" *)
  output write;
  (* src = "serial_ctrl.v:12.12-12.32" *)
  output write_shift_register;
  not_gate _097_ (
    .I(curr_state_pre[0]),
    .O(_048_)
  );
  not_gate _098_ (
    .I(curr_state[1]),
    .O(_049_)
  );
  not_gate _099_ (
    .I(curr_state[3]),
    .O(_050_)
  );
  not_gate _100_ (
    .I(curr_state[2]),
    .O(_051_)
  );
  not_gate _101_ (
    .I(data_in),
    .O(_052_)
  );
  nor_gate _102_ (
    .A(curr_state[0]),
    .B(curr_state[1]),
    .O(_053_)
  );
  and_gate _103_ (
    .A(_050_),
    .B(curr_state[2]),
    .O(_054_)
  );
  nand_gate _104_ (
    .A(_053_),
    .B(_054_),
    .O(reset_shift_reg_out)
  );
  and_gate _105_ (
    .A(_051_),
    .B(_053_),
    .O(_055_)
  );
  nand_gate _106_ (
    .A(curr_state[3]),
    .B(_055_),
    .O(_056_)
  );
  not_gate _107_ (
    .I(_056_),
    .O(write)
  );
  and_gate _108_ (
    .A(curr_state[0]),
    .B(_049_),
    .O(_057_)
  );
  nand_gate _109_ (
    .A(_054_),
    .B(_057_),
    .O(_058_)
  );
  not_gate _110_ (
    .I(_058_),
    .O(write_shift_register)
  );
  nand_gate _111_ (
    .A(_056_),
    .B(_058_),
    .O(enable_shift_register)
  );
  nand_gate _112_ (
    .A(_048_),
    .B(curr_state_post[3]),
    .O(_059_)
  );
  nand_gate _113_ (
    .A(curr_state_post[0]),
    .B(curr_state_post[2]),
    .O(_060_)
  );
  nand_gate _114_ (
    .A(_059_),
    .B(_060_),
    .O(_061_)
  );
  or_gate _115_ (
    .A(curr_state_post[0]),
    .B(curr_state_post[2]),
    .O(_062_)
  );
  or_gate _116_ (
    .A(_048_),
    .B(curr_state_post[3]),
    .O(_063_)
  );
  nand_gate _117_ (
    .A(_062_),
    .B(_063_),
    .O(_064_)
  );
  nand_gate _118_ (
    .A(_061_),
    .B(_064_),
    .O(_065_)
  );
  or_gate _119_ (
    .A(curr_state_post[1]),
    .B(_065_),
    .O(_066_)
  );
  and_gate _120_ (
    .A(curr_state_pre[3]),
    .B(_048_),
    .O(_067_)
  );
  or_gate _121_ (
    .A(curr_state_pre[2]),
    .B(_067_),
    .O(_068_)
  );
  or_gate _122_ (
    .A(curr_state_pre[3]),
    .B(_048_),
    .O(_069_)
  );
  and_gate _123_ (
    .A(curr_state_pre[2]),
    .B(_069_),
    .O(_070_)
  );
  nor_gate _124_ (
    .A(curr_state_pre[1]),
    .B(_070_),
    .O(_071_)
  );
  and_gate _125_ (
    .A(_068_),
    .B(_071_),
    .O(_072_)
  );
  nand_gate _126_ (
    .A(_066_),
    .B(_072_),
    .O(reset_count_out)
  );
  nor_gate _127_ (
    .A(curr_state[3]),
    .B(curr_state[2]),
    .O(_073_)
  );
  and_gate _128_ (
    .A(curr_state[0]),
    .B(_073_),
    .O(_074_)
  );
  nand_gate _129_ (
    .A(curr_state[1]),
    .B(_074_),
    .O(_075_)
  );
  nand_gate _130_ (
    .A(reset_shift_reg_out),
    .B(_075_),
    .O(_000_)
  );
  or_gate _131_ (
    .A(rst_reg[1]),
    .B(rst_reg[0]),
    .O(_076_)
  );
  or_gate _132_ (
    .A(rst_reg[2]),
    .B(_076_),
    .O(_077_)
  );
  or_gate _133_ (
    .A(rst_reg[3]),
    .B(_077_),
    .O(_078_)
  );
  or_gate _134_ (
    .A(rst_reg[4]),
    .B(_078_),
    .O(_079_)
  );
  or_gate _135_ (
    .A(_050_),
    .B(_055_),
    .O(_080_)
  );
  nor_gate _136_ (
    .A(curr_state[0]),
    .B(_049_),
    .O(_081_)
  );
  not_gate _137_ (
    .I(_081_),
    .O(_082_)
  );
  and_gate _138_ (
    .A(_073_),
    .B(_081_),
    .O(_083_)
  );
  nand_gate _139_ (
    .A(cmd_reg[2]),
    .B(cmd_reg[4]),
    .O(_084_)
  );
  nor_gate _140_ (
    .A(cmd_reg[3]),
    .B(_084_),
    .O(_085_)
  );
  and_gate _141_ (
    .A(_083_),
    .B(_085_),
    .O(_086_)
  );
  nand_gate _142_ (
    .A(data_in),
    .B(_086_),
    .O(_087_)
  );
  and_gate _143_ (
    .A(_080_),
    .B(_087_),
    .O(_088_)
  );
  nand_gate _144_ (
    .A(_080_),
    .B(_087_),
    .O(_089_)
  );
  nand_gate _145_ (
    .A(curr_state_pre[0]),
    .B(_089_),
    .O(_090_)
  );
  and_gate _146_ (
    .A(_052_),
    .B(cmd_reg[1]),
    .O(_091_)
  );
  nand_gate _147_ (
    .A(_086_),
    .B(_091_),
    .O(_092_)
  );
  nand_gate _148_ (
    .A(count_reached_in),
    .B(write),
    .O(_093_)
  );
  nand_gate _149_ (
    .A(_054_),
    .B(_082_),
    .O(_094_)
  );
  and_gate _150_ (
    .A(_075_),
    .B(_094_),
    .O(_095_)
  );
  and_gate _151_ (
    .A(_093_),
    .B(_095_),
    .O(_096_)
  );
  and_gate _152_ (
    .A(_092_),
    .B(_096_),
    .O(_015_)
  );
  nand_gate _153_ (
    .A(_090_),
    .B(_015_),
    .O(_016_)
  );
  and_gate _154_ (
    .A(_079_),
    .B(_016_),
    .O(_005_)
  );
  nor_gate _155_ (
    .A(data_in),
    .B(cmd_reg[0]),
    .O(_017_)
  );
  nand_gate _156_ (
    .A(_085_),
    .B(_017_),
    .O(_018_)
  );
  nand_gate _157_ (
    .A(_083_),
    .B(_018_),
    .O(_019_)
  );
  nand_gate _158_ (
    .A(_049_),
    .B(_074_),
    .O(_020_)
  );
  and_gate _159_ (
    .A(_019_),
    .B(_020_),
    .O(_021_)
  );
  and_gate _160_ (
    .A(_093_),
    .B(_021_),
    .O(_022_)
  );
  nand_gate _161_ (
    .A(_088_),
    .B(_022_),
    .O(_023_)
  );
  or_gate _162_ (
    .A(curr_state_pre[1]),
    .B(_088_),
    .O(_024_)
  );
  and_gate _163_ (
    .A(_079_),
    .B(_024_),
    .O(_025_)
  );
  and_gate _164_ (
    .A(_023_),
    .B(_025_),
    .O(_006_)
  );
  or_gate _165_ (
    .A(count_reached_in),
    .B(_056_),
    .O(_026_)
  );
  or_gate _166_ (
    .A(curr_state[3]),
    .B(_055_),
    .O(_027_)
  );
  nand_gate _167_ (
    .A(_026_),
    .B(_027_),
    .O(_028_)
  );
  nand_gate _168_ (
    .A(cmd_reg[0]),
    .B(_091_),
    .O(_029_)
  );
  nand_gate _169_ (
    .A(_086_),
    .B(_029_),
    .O(_030_)
  );
  or_gate _170_ (
    .A(count_reached_in),
    .B(_058_),
    .O(_031_)
  );
  and_gate _171_ (
    .A(_030_),
    .B(_031_),
    .O(_032_)
  );
  nand_gate _172_ (
    .A(_028_),
    .B(_032_),
    .O(_033_)
  );
  or_gate _173_ (
    .A(curr_state_pre[2]),
    .B(_088_),
    .O(_034_)
  );
  and_gate _174_ (
    .A(_079_),
    .B(_034_),
    .O(_035_)
  );
  and_gate _175_ (
    .A(_033_),
    .B(_035_),
    .O(_007_)
  );
  nand_gate _176_ (
    .A(curr_state_pre[3]),
    .B(_089_),
    .O(_036_)
  );
  nand_gate _177_ (
    .A(_054_),
    .B(_081_),
    .O(_037_)
  );
  and_gate _178_ (
    .A(_026_),
    .B(_037_),
    .O(_038_)
  );
  nand_gate _179_ (
    .A(_036_),
    .B(_038_),
    .O(_039_)
  );
  and_gate _180_ (
    .A(_079_),
    .B(_039_),
    .O(_008_)
  );
  and_gate _181_ (
    .A(data_in),
    .B(_020_),
    .O(_009_)
  );
  and_gate _182_ (
    .A(cmd_reg[0]),
    .B(_020_),
    .O(_010_)
  );
  and_gate _183_ (
    .A(cmd_reg[1]),
    .B(_020_),
    .O(_011_)
  );
  and_gate _184_ (
    .A(cmd_reg[2]),
    .B(_020_),
    .O(_012_)
  );
  and_gate _185_ (
    .A(cmd_reg[3]),
    .B(_020_),
    .O(_013_)
  );
  nand_gate _186_ (
    .A(data_in),
    .B(rst_reg[0]),
    .O(_014_)
  );
  nand_gate _187_ (
    .A(rst_reg[1]),
    .B(rst_reg[0]),
    .O(_040_)
  );
  and_gate _188_ (
    .A(data_in),
    .B(_040_),
    .O(_041_)
  );
  nand_gate _189_ (
    .A(_076_),
    .B(_041_),
    .O(_001_)
  );
  nand_gate _190_ (
    .A(rst_reg[2]),
    .B(_076_),
    .O(_042_)
  );
  and_gate _191_ (
    .A(data_in),
    .B(_042_),
    .O(_043_)
  );
  nand_gate _192_ (
    .A(_077_),
    .B(_043_),
    .O(_002_)
  );
  nand_gate _193_ (
    .A(rst_reg[3]),
    .B(_077_),
    .O(_044_)
  );
  and_gate _194_ (
    .A(data_in),
    .B(_044_),
    .O(_045_)
  );
  nand_gate _195_ (
    .A(_078_),
    .B(_045_),
    .O(_003_)
  );
  nand_gate _196_ (
    .A(rst_reg[4]),
    .B(_078_),
    .O(_046_)
  );
  and_gate _197_ (
    .A(data_in),
    .B(_046_),
    .O(_047_)
  );
  nand_gate _198_ (
    .A(_079_),
    .B(_047_),
    .O(_004_)
  );
  (* src = "serial_ctrl.v:168.5-170.8" *)
  dffpq _199_ (
    .CLK(clk),
    .D(curr_state[0]),
    .Q(curr_state_post[0])
  );
  (* src = "serial_ctrl.v:168.5-170.8" *)
  dffpq _200_ (
    .CLK(clk),
    .D(curr_state[1]),
    .Q(curr_state_post[1])
  );
  (* src = "serial_ctrl.v:168.5-170.8" *)
  dffpq _201_ (
    .CLK(clk),
    .D(curr_state[2]),
    .Q(curr_state_post[2])
  );
  (* src = "serial_ctrl.v:168.5-170.8" *)
  dffpq _202_ (
    .CLK(clk),
    .D(curr_state[3]),
    .Q(curr_state_post[3])
  );
  (* src = "serial_ctrl.v:165.5-167.8" *)
  dffnq _203_ (
    .CLK(clk),
    .D(curr_state_pre[0]),
    .Q(curr_state[0])
  );
  (* src = "serial_ctrl.v:165.5-167.8" *)
  dffnq _204_ (
    .CLK(clk),
    .D(curr_state_pre[1]),
    .Q(curr_state[1])
  );
  (* src = "serial_ctrl.v:165.5-167.8" *)
  dffnq _205_ (
    .CLK(clk),
    .D(curr_state_pre[2]),
    .Q(curr_state[2])
  );
  (* src = "serial_ctrl.v:165.5-167.8" *)
  dffnq _206_ (
    .CLK(clk),
    .D(curr_state_pre[3]),
    .Q(curr_state[3])
  );
  (* src = "serial_ctrl.v:101.5-164.8" *)
  dffpq _207_ (
    .CLK(clk),
    .D(_005_),
    .Q(curr_state_pre[0])
  );
  (* src = "serial_ctrl.v:101.5-164.8" *)
  dffpq _208_ (
    .CLK(clk),
    .D(_006_),
    .Q(curr_state_pre[1])
  );
  (* src = "serial_ctrl.v:101.5-164.8" *)
  dffpq _209_ (
    .CLK(clk),
    .D(_007_),
    .Q(curr_state_pre[2])
  );
  (* src = "serial_ctrl.v:101.5-164.8" *)
  dffpq _210_ (
    .CLK(clk),
    .D(_008_),
    .Q(curr_state_pre[3])
  );
  (* src = "serial_ctrl.v:89.5-91.8" *)
  dffnq _211_ (
    .CLK(clk),
    .D(cmd_reg_pre[0]),
    .Q(cmd_reg[0])
  );
  (* src = "serial_ctrl.v:89.5-91.8" *)
  dffnq _212_ (
    .CLK(clk),
    .D(cmd_reg_pre[1]),
    .Q(cmd_reg[1])
  );
  (* src = "serial_ctrl.v:89.5-91.8" *)
  dffnq _213_ (
    .CLK(clk),
    .D(cmd_reg_pre[2]),
    .Q(cmd_reg[2])
  );
  (* src = "serial_ctrl.v:89.5-91.8" *)
  dffnq _214_ (
    .CLK(clk),
    .D(cmd_reg_pre[3]),
    .Q(cmd_reg[3])
  );
  (* src = "serial_ctrl.v:89.5-91.8" *)
  dffnq _215_ (
    .CLK(clk),
    .D(cmd_reg_pre[4]),
    .Q(cmd_reg[4])
  );
  (* src = "serial_ctrl.v:74.5-81.8" *)
  dffpq _216_ (
    .CLK(clk),
    .D(_000_),
    .Q(update)
  );
  (* src = "serial_ctrl.v:92.5-99.8" *)
  dffpq _217_ (
    .CLK(clk),
    .D(_009_),
    .Q(cmd_reg_pre[0])
  );
  (* src = "serial_ctrl.v:92.5-99.8" *)
  dffpq _218_ (
    .CLK(clk),
    .D(_010_),
    .Q(cmd_reg_pre[1])
  );
  (* src = "serial_ctrl.v:92.5-99.8" *)
  dffpq _219_ (
    .CLK(clk),
    .D(_011_),
    .Q(cmd_reg_pre[2])
  );
  (* src = "serial_ctrl.v:92.5-99.8" *)
  dffpq _220_ (
    .CLK(clk),
    .D(_012_),
    .Q(cmd_reg_pre[3])
  );
  (* src = "serial_ctrl.v:92.5-99.8" *)
  dffpq _221_ (
    .CLK(clk),
    .D(_013_),
    .Q(cmd_reg_pre[4])
  );
  (* src = "serial_ctrl.v:27.5-29.8" *)
  dffnq _222_ (
    .CLK(clk),
    .D(rst_reg_pre[0]),
    .Q(rst_reg[0])
  );
  (* src = "serial_ctrl.v:27.5-29.8" *)
  dffnq _223_ (
    .CLK(clk),
    .D(rst_reg_pre[1]),
    .Q(rst_reg[1])
  );
  (* src = "serial_ctrl.v:27.5-29.8" *)
  dffnq _224_ (
    .CLK(clk),
    .D(rst_reg_pre[2]),
    .Q(rst_reg[2])
  );
  (* src = "serial_ctrl.v:27.5-29.8" *)
  dffnq _225_ (
    .CLK(clk),
    .D(rst_reg_pre[3]),
    .Q(rst_reg[3])
  );
  (* src = "serial_ctrl.v:27.5-29.8" *)
  dffnq _226_ (
    .CLK(clk),
    .D(rst_reg_pre[4]),
    .Q(rst_reg[4])
  );
  (* src = "serial_ctrl.v:30.5-37.8" *)
  dffpq _227_ (
    .CLK(clk),
    .D(_014_),
    .Q(rst_reg_pre[0])
  );
  (* src = "serial_ctrl.v:30.5-37.8" *)
  dffpq _228_ (
    .CLK(clk),
    .D(_001_),
    .Q(rst_reg_pre[1])
  );
  (* src = "serial_ctrl.v:30.5-37.8" *)
  dffpq _229_ (
    .CLK(clk),
    .D(_002_),
    .Q(rst_reg_pre[2])
  );
  (* src = "serial_ctrl.v:30.5-37.8" *)
  dffpq _230_ (
    .CLK(clk),
    .D(_003_),
    .Q(rst_reg_pre[3])
  );
  (* src = "serial_ctrl.v:30.5-37.8" *)
  dffpq _231_ (
    .CLK(clk),
    .D(_004_),
    .Q(rst_reg_pre[4])
  );
endmodule

(* top =  1  *)
(* src = "toplevel.v:1.1-56.10" *)
module serial_interface(clk, data_inout, bit_out);
  (* src = "toplevel.v:7.22-7.29" *)
  output [7:0] bit_out;
  (* src = "toplevel.v:4.11-4.14" *)
  input clk;
  (* src = "toplevel.v:10.6-10.19" *)
  wire count_reached;
  (* src = "toplevel.v:5.11-5.21" *)
  inout data_inout;
  (* src = "toplevel.v:18.6-18.14" *)
  wire data_out;
  (* src = "toplevel.v:14.6-14.27" *)
  wire enable_shift_register;
  (* src = "toplevel.v:9.6-9.19" *)
  wire reset_counter;
  (* src = "toplevel.v:13.6-13.26" *)
  wire reset_shift_register;
  (* src = "toplevel.v:12.6-12.12" *)
  wire update;
  (* src = "toplevel.v:24.9-24.14" *)
  wire write;
  (* src = "toplevel.v:36.27-36.47" *)
  wire write_shift_register;
  (* module_not_derived = 32'd1 *)
  (* src = "toplevel.v:21.6-25.2" *)
  tbuf bidir_data_buffer (
    .EN(write),
    .I(data_out),
    .O(data_inout)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "toplevel.v:27.13-37.2" *)
  serial_ctrl control (
    .clk(clk),
    .count_reached_in(count_reached),
    .data_in(data_inout),
    .enable_shift_register(enable_shift_register),
    .reset_count_out(reset_counter),
    .reset_shift_reg_out(reset_shift_register),
    .update(update),
    .write(write),
    .write_shift_register(write_shift_register)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "toplevel.v:39.13-43.2" *)
  bit_counter counter (
    .clk(clk),
    .count_reached_out(count_reached),
    .reset_in(reset_counter)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "toplevel.v:45.16-54.2" *)
  shift_register daisychain (
    .bit_out(bit_out),
    .clk(clk),
    .data_in(data_inout),
    .data_out(data_out),
    .enable(enable_shift_register),
    .reset(reset_shift_register),
    .update(update),
    .write(write_shift_register)
  );
endmodule

(* src = "shift_register.v:2.1-37.10" *)
module shift_register(clk, data_in, update, reset, enable, write, data_out, bit_out);
  (* src = "shift_register.v:11.26-11.33" *)
  output [7:0] bit_out;
  (* src = "shift_register.v:19.20-19.29" *)
  wire [7:0] cells_out;
  (* src = "shift_register.v:4.15-4.18" *)
  input clk;
  (* src = "shift_register.v:5.15-5.22" *)
  input data_in;
  (* src = "shift_register.v:10.16-10.24" *)
  output data_out;
  (* src = "shift_register.v:8.15-8.21" *)
  input enable;
  (* src = "shift_register.v:7.15-7.20" *)
  input reset;
  (* src = "shift_register.v:6.15-6.21" *)
  input update;
  (* src = "shift_register.v:9.15-9.20" *)
  input write;
  (* module_not_derived = 32'd1 *)
  (* src = "shift_register.v:28.19-36.6" *)
  register_cell \regcell[0]  (
    .bit_out(bit_out[0]),
    .chain_in(cells_out[1]),
    .chain_out(data_out),
    .clk(clk),
    .enable(enable),
    .reset(reset),
    .update(update)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "shift_register.v:28.19-36.6" *)
  register_cell \regcell[1]  (
    .bit_out(bit_out[1]),
    .chain_in(cells_out[2]),
    .chain_out(cells_out[1]),
    .clk(clk),
    .enable(enable),
    .reset(reset),
    .update(update)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "shift_register.v:28.19-36.6" *)
  register_cell \regcell[2]  (
    .bit_out(bit_out[2]),
    .chain_in(cells_out[3]),
    .chain_out(cells_out[2]),
    .clk(clk),
    .enable(enable),
    .reset(reset),
    .update(update)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "shift_register.v:28.19-36.6" *)
  register_cell \regcell[3]  (
    .bit_out(bit_out[3]),
    .chain_in(cells_out[4]),
    .chain_out(cells_out[3]),
    .clk(clk),
    .enable(enable),
    .reset(reset),
    .update(update)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "shift_register.v:28.19-36.6" *)
  register_cell \regcell[4]  (
    .bit_out(bit_out[4]),
    .chain_in(cells_out[5]),
    .chain_out(cells_out[4]),
    .clk(clk),
    .enable(enable),
    .reset(reset),
    .update(update)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "shift_register.v:28.19-36.6" *)
  register_cell \regcell[5]  (
    .bit_out(bit_out[5]),
    .chain_in(cells_out[6]),
    .chain_out(cells_out[5]),
    .clk(clk),
    .enable(enable),
    .reset(reset),
    .update(update)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "shift_register.v:28.19-36.6" *)
  register_cell \regcell[6]  (
    .bit_out(bit_out[6]),
    .chain_in(cells_out[7]),
    .chain_out(cells_out[6]),
    .clk(clk),
    .enable(enable),
    .reset(reset),
    .update(update)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "shift_register.v:28.19-36.6" *)
  register_cell \regcell[7]  (
    .bit_out(bit_out[7]),
    .chain_in(data_in),
    .chain_out(cells_out[7]),
    .clk(clk),
    .enable(enable),
    .reset(reset),
    .update(update)
  );
  assign cells_out[0] = data_out;
endmodule
