/* Generated by Yosys 0.12 (git sha1 UNKNOWN, gcc 12.1.0 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fPIC -Os) */

(* src = "bit_counter.v:1.1-30.10" *)
module bit_counter(clk, reset_in, count_reached_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  (* src = "bit_counter.v:3.11-3.14" *)
  input clk;
  (* src = "bit_counter.v:11.27-11.32" *)
  wire [3:0] count;
  (* src = "bit_counter.v:12.27-12.36" *)
  wire [3:0] count_pre;
  (* src = "bit_counter.v:5.12-5.29" *)
  output count_reached_out;
  (* src = "bit_counter.v:4.11-4.19" *)
  input reset_in;
  not_gate _18_ (
    .I(count_pre[2]),
    .O(_04_)
  );
  not_gate _19_ (
    .I(count[2]),
    .O(_05_)
  );
  not_gate _20_ (
    .I(reset_in),
    .O(_06_)
  );
  nor_gate _21_ (
    .A(count_pre[1]),
    .B(count_pre[0]),
    .O(_07_)
  );
  not_gate _22_ (
    .I(_07_),
    .O(_08_)
  );
  nand_gate _23_ (
    .A(_04_),
    .B(count_pre[3]),
    .O(_09_)
  );
  nor_gate _24_ (
    .A(_08_),
    .B(_09_),
    .O(count_reached_out)
  );
  nand_gate _25_ (
    .A(count[0]),
    .B(reset_in),
    .O(_00_)
  );
  nor_gate _26_ (
    .A(count[0]),
    .B(count[1]),
    .O(_10_)
  );
  nand_gate _27_ (
    .A(count[0]),
    .B(count[1]),
    .O(_11_)
  );
  nand_gate _28_ (
    .A(reset_in),
    .B(_11_),
    .O(_12_)
  );
  nor_gate _29_ (
    .A(_10_),
    .B(_12_),
    .O(_13_)
  );
  not_gate _30_ (
    .I(_13_),
    .O(_01_)
  );
  nand_gate _31_ (
    .A(_05_),
    .B(_10_),
    .O(_14_)
  );
  nor_gate _32_ (
    .A(_05_),
    .B(_10_),
    .O(_15_)
  );
  nor_gate _33_ (
    .A(_06_),
    .B(_15_),
    .O(_16_)
  );
  nand_gate _34_ (
    .A(_14_),
    .B(_16_),
    .O(_02_)
  );
  xor_gate _35_ (
    .A(count[3]),
    .B(_14_),
    .O(_17_)
  );
  nand_gate _36_ (
    .A(reset_in),
    .B(_17_),
    .O(_03_)
  );
  (* src = "bit_counter.v:17.1-24.4" *)
  dffnq _37_ (
    .CLK(clk),
    .D(_00_),
    .Q(count_pre[0])
  );
  (* src = "bit_counter.v:17.1-24.4" *)
  dffnq _38_ (
    .CLK(clk),
    .D(_01_),
    .Q(count_pre[1])
  );
  (* src = "bit_counter.v:17.1-24.4" *)
  dffnq _39_ (
    .CLK(clk),
    .D(_02_),
    .Q(count_pre[2])
  );
  (* src = "bit_counter.v:17.1-24.4" *)
  dffnq _40_ (
    .CLK(clk),
    .D(_03_),
    .Q(count_pre[3])
  );
  (* src = "bit_counter.v:26.1-28.4" *)
  dffpq _41_ (
    .CLK(clk),
    .D(count_pre[0]),
    .Q(count[0])
  );
  (* src = "bit_counter.v:26.1-28.4" *)
  dffpq _42_ (
    .CLK(clk),
    .D(count_pre[1]),
    .Q(count[1])
  );
  (* src = "bit_counter.v:26.1-28.4" *)
  dffpq _43_ (
    .CLK(clk),
    .D(count_pre[2]),
    .Q(count[2])
  );
  (* src = "bit_counter.v:26.1-28.4" *)
  dffpq _44_ (
    .CLK(clk),
    .D(count_pre[3]),
    .Q(count[3])
  );
endmodule

(* src = "register_cell.v:2.1-45.10" *)
module register_cell(chain_in, update, clk, reset, enable, chain_out, bit_out);
  (* src = "register_cell.v:22.5-29.8" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "register_cell.v:10.10-10.17" *)
  output bit_out;
  (* src = "register_cell.v:4.9-4.17" *)
  input chain_in;
  (* src = "register_cell.v:9.10-9.19" *)
  output chain_out;
  (* src = "register_cell.v:6.9-6.12" *)
  input clk;
  (* src = "register_cell.v:8.9-8.15" *)
  input enable;
  (* src = "register_cell.v:21.9-21.14" *)
  wire ff_in;
  (* src = "register_cell.v:7.9-7.14" *)
  input reset;
  (* src = "register_cell.v:5.9-5.15" *)
  input update;
  not_gate _06_ (
    .I(enable),
    .O(_04_)
  );
  nand_gate _07_ (
    .A(chain_in),
    .B(enable),
    .O(_05_)
  );
  nand_gate _08_ (
    .A(chain_out),
    .B(_04_),
    .O(_02_)
  );
  nand_gate _09_ (
    .A(_05_),
    .B(_02_),
    .O(_00_)
  );
  nand_gate _10_ (
    .A(ff_in),
    .B(reset),
    .O(_03_)
  );
  not_gate _11_ (
    .I(_03_),
    .O(_01_)
  );
  (* src = "register_cell.v:37.5-44.8" *)
  dffpq _12_ (
    .CLK(update),
    .D(_01_),
    .Q(bit_out)
  );
  (* src = "register_cell.v:32.5-34.8" *)
  dffnq _13_ (
    .CLK(clk),
    .D(ff_in),
    .Q(chain_out)
  );
  (* src = "register_cell.v:22.5-29.8" *)
  dffpq _14_ (
    .CLK(clk),
    .D(_00_),
    .Q(ff_in)
  );
endmodule

(* src = "serial_ctrl.v:1.1-180.10" *)
module serial_ctrl(clk, data_in, write, count_reached_in, data_out_shift_reg_in, reset_count_out, update, reset_shift_reg_out, enable_shift_register, write_shift_register);
  (* src = "serial_ctrl.v:83.5-90.8" *)
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  (* src = "serial_ctrl.v:3.11-3.14" *)
  input clk;
  (* src = "serial_ctrl.v:96.27-96.34" *)
  wire [4:0] cmd_reg;
  (* src = "serial_ctrl.v:97.27-97.38" *)
  wire [4:0] cmd_reg_pre;
  (* src = "serial_ctrl.v:6.11-6.27" *)
  input count_reached_in;
  (* src = "serial_ctrl.v:68.15-68.25" *)
  wire [3:0] curr_state;
  (* src = "serial_ctrl.v:69.15-69.30" *)
  wire [3:0] curr_state_post;
  (* src = "serial_ctrl.v:67.15-67.29" *)
  wire [3:0] curr_state_pre;
  (* src = "serial_ctrl.v:4.11-4.18" *)
  input data_in;
  (* src = "serial_ctrl.v:7.11-7.32" *)
  input data_out_shift_reg_in;
  (* src = "serial_ctrl.v:11.12-11.33" *)
  output enable_shift_register;
  (* src = "serial_ctrl.v:8.12-8.27" *)
  output reset_count_out;
  (* src = "serial_ctrl.v:10.12-10.31" *)
  output reset_shift_reg_out;
  (* src = "serial_ctrl.v:26.27-26.34" *)
  wire [4:0] rst_reg;
  (* src = "serial_ctrl.v:26.36-26.47" *)
  wire [4:0] rst_reg_pre;
  (* src = "serial_ctrl.v:9.12-9.18" *)
  output update;
  (* src = "serial_ctrl.v:5.12-5.17" *)
  output write;
  (* src = "serial_ctrl.v:12.12-12.32" *)
  output write_shift_register;
  not_gate _126_ (
    .I(curr_state_pre[3]),
    .O(_077_)
  );
  not_gate _127_ (
    .I(curr_state_pre[2]),
    .O(_078_)
  );
  not_gate _128_ (
    .I(curr_state_pre[1]),
    .O(_079_)
  );
  not_gate _129_ (
    .I(curr_state_pre[0]),
    .O(_080_)
  );
  not_gate _130_ (
    .I(curr_state[0]),
    .O(_081_)
  );
  not_gate _131_ (
    .I(curr_state[1]),
    .O(_082_)
  );
  not_gate _132_ (
    .I(curr_state[3]),
    .O(_083_)
  );
  not_gate _133_ (
    .I(curr_state[2]),
    .O(_084_)
  );
  not_gate _134_ (
    .I(cmd_reg[3]),
    .O(_085_)
  );
  not_gate _135_ (
    .I(cmd_reg[2]),
    .O(_086_)
  );
  not_gate _136_ (
    .I(data_in),
    .O(_087_)
  );
  not_gate _137_ (
    .I(cmd_reg[0]),
    .O(_088_)
  );
  not_gate _138_ (
    .I(cmd_reg[1]),
    .O(_089_)
  );
  not_gate _139_ (
    .I(rst_reg[1]),
    .O(_090_)
  );
  not_gate _140_ (
    .I(rst_reg[0]),
    .O(_091_)
  );
  not_gate _141_ (
    .I(rst_reg[3]),
    .O(_092_)
  );
  not_gate _142_ (
    .I(rst_reg[2]),
    .O(_093_)
  );
  not_gate _143_ (
    .I(rst_reg[4]),
    .O(_094_)
  );
  not_gate _144_ (
    .I(count_reached_in),
    .O(_095_)
  );
  nor_gate _145_ (
    .A(curr_state[0]),
    .B(curr_state[1]),
    .O(_096_)
  );
  not_gate _146_ (
    .I(_096_),
    .O(_097_)
  );
  nor_gate _147_ (
    .A(curr_state[3]),
    .B(_084_),
    .O(_098_)
  );
  not_gate _148_ (
    .I(_098_),
    .O(_099_)
  );
  nand_gate _149_ (
    .A(_096_),
    .B(_098_),
    .O(reset_shift_reg_out)
  );
  nor_gate _150_ (
    .A(curr_state[2]),
    .B(_097_),
    .O(_100_)
  );
  nand_gate _151_ (
    .A(_084_),
    .B(_096_),
    .O(_101_)
  );
  nand_gate _152_ (
    .A(curr_state[3]),
    .B(_100_),
    .O(_102_)
  );
  not_gate _153_ (
    .I(_102_),
    .O(write)
  );
  nand_gate _154_ (
    .A(curr_state[0]),
    .B(_082_),
    .O(_103_)
  );
  nor_gate _155_ (
    .A(_099_),
    .B(_103_),
    .O(write_shift_register)
  );
  not_gate _156_ (
    .I(write_shift_register),
    .O(_104_)
  );
  nand_gate _157_ (
    .A(_102_),
    .B(_104_),
    .O(enable_shift_register)
  );
  nand_gate _158_ (
    .A(_080_),
    .B(curr_state_post[3]),
    .O(_105_)
  );
  nand_gate _159_ (
    .A(curr_state_post[0]),
    .B(curr_state_post[2]),
    .O(_106_)
  );
  nand_gate _160_ (
    .A(_105_),
    .B(_106_),
    .O(_107_)
  );
  nor_gate _161_ (
    .A(curr_state_post[0]),
    .B(curr_state_post[2]),
    .O(_108_)
  );
  nor_gate _162_ (
    .A(_080_),
    .B(curr_state_post[3]),
    .O(_109_)
  );
  nor_gate _163_ (
    .A(_108_),
    .B(_109_),
    .O(_110_)
  );
  nor_gate _164_ (
    .A(curr_state_post[1]),
    .B(_110_),
    .O(_111_)
  );
  nand_gate _165_ (
    .A(_107_),
    .B(_111_),
    .O(_112_)
  );
  nor_gate _166_ (
    .A(_077_),
    .B(curr_state_pre[0]),
    .O(_113_)
  );
  nor_gate _167_ (
    .A(curr_state_pre[2]),
    .B(_113_),
    .O(_114_)
  );
  nand_gate _168_ (
    .A(_077_),
    .B(curr_state_pre[0]),
    .O(_115_)
  );
  nand_gate _169_ (
    .A(curr_state_pre[2]),
    .B(_115_),
    .O(_116_)
  );
  nand_gate _170_ (
    .A(_079_),
    .B(_116_),
    .O(_117_)
  );
  nor_gate _171_ (
    .A(_114_),
    .B(_117_),
    .O(_118_)
  );
  nand_gate _172_ (
    .A(_112_),
    .B(_118_),
    .O(reset_count_out)
  );
  nor_gate _173_ (
    .A(curr_state[3]),
    .B(curr_state[2]),
    .O(_119_)
  );
  not_gate _174_ (
    .I(_119_),
    .O(_120_)
  );
  nand_gate _175_ (
    .A(curr_state[0]),
    .B(_119_),
    .O(_121_)
  );
  not_gate _176_ (
    .I(_121_),
    .O(_122_)
  );
  nand_gate _177_ (
    .A(curr_state[1]),
    .B(_122_),
    .O(_123_)
  );
  nand_gate _178_ (
    .A(reset_shift_reg_out),
    .B(_123_),
    .O(_000_)
  );
  nor_gate _179_ (
    .A(rst_reg[1]),
    .B(rst_reg[0]),
    .O(_124_)
  );
  nand_gate _180_ (
    .A(_090_),
    .B(_091_),
    .O(_125_)
  );
  nor_gate _181_ (
    .A(rst_reg[2]),
    .B(_125_),
    .O(_015_)
  );
  nand_gate _182_ (
    .A(_093_),
    .B(_124_),
    .O(_016_)
  );
  nor_gate _183_ (
    .A(rst_reg[3]),
    .B(_016_),
    .O(_017_)
  );
  nand_gate _184_ (
    .A(_092_),
    .B(_015_),
    .O(_018_)
  );
  nor_gate _185_ (
    .A(rst_reg[4]),
    .B(_018_),
    .O(_019_)
  );
  nand_gate _186_ (
    .A(_094_),
    .B(_017_),
    .O(_020_)
  );
  nor_gate _187_ (
    .A(_083_),
    .B(_100_),
    .O(_021_)
  );
  nand_gate _188_ (
    .A(curr_state[3]),
    .B(_101_),
    .O(_022_)
  );
  nor_gate _189_ (
    .A(curr_state[0]),
    .B(_082_),
    .O(_023_)
  );
  nand_gate _190_ (
    .A(_081_),
    .B(curr_state[1]),
    .O(_024_)
  );
  nor_gate _191_ (
    .A(_120_),
    .B(_024_),
    .O(_025_)
  );
  nand_gate _192_ (
    .A(_119_),
    .B(_023_),
    .O(_026_)
  );
  nand_gate _193_ (
    .A(cmd_reg[2]),
    .B(cmd_reg[4]),
    .O(_027_)
  );
  nor_gate _194_ (
    .A(cmd_reg[3]),
    .B(_027_),
    .O(_028_)
  );
  not_gate _195_ (
    .I(_028_),
    .O(_029_)
  );
  nor_gate _196_ (
    .A(_026_),
    .B(_029_),
    .O(_030_)
  );
  nand_gate _197_ (
    .A(_025_),
    .B(_028_),
    .O(_031_)
  );
  nor_gate _198_ (
    .A(_087_),
    .B(_031_),
    .O(_032_)
  );
  nand_gate _199_ (
    .A(data_in),
    .B(_030_),
    .O(_033_)
  );
  nor_gate _200_ (
    .A(_021_),
    .B(_032_),
    .O(_034_)
  );
  nand_gate _201_ (
    .A(_022_),
    .B(_033_),
    .O(_035_)
  );
  nor_gate _202_ (
    .A(_080_),
    .B(_034_),
    .O(_036_)
  );
  nor_gate _203_ (
    .A(data_in),
    .B(_089_),
    .O(_037_)
  );
  nand_gate _204_ (
    .A(_030_),
    .B(_037_),
    .O(_038_)
  );
  nor_gate _205_ (
    .A(_095_),
    .B(_102_),
    .O(_039_)
  );
  nand_gate _206_ (
    .A(_098_),
    .B(_024_),
    .O(_040_)
  );
  nand_gate _207_ (
    .A(_123_),
    .B(_040_),
    .O(_041_)
  );
  nor_gate _208_ (
    .A(_039_),
    .B(_041_),
    .O(_042_)
  );
  nand_gate _209_ (
    .A(_038_),
    .B(_042_),
    .O(_043_)
  );
  nor_gate _210_ (
    .A(_036_),
    .B(_043_),
    .O(_044_)
  );
  nor_gate _211_ (
    .A(_019_),
    .B(_044_),
    .O(_005_)
  );
  nand_gate _212_ (
    .A(_087_),
    .B(_088_),
    .O(_045_)
  );
  nor_gate _213_ (
    .A(_029_),
    .B(_045_),
    .O(_046_)
  );
  nor_gate _214_ (
    .A(_026_),
    .B(_046_),
    .O(_047_)
  );
  nor_gate _215_ (
    .A(curr_state[1]),
    .B(_121_),
    .O(_048_)
  );
  nor_gate _216_ (
    .A(_039_),
    .B(_047_),
    .O(_049_)
  );
  nand_gate _217_ (
    .A(_034_),
    .B(_049_),
    .O(_050_)
  );
  nor_gate _218_ (
    .A(_048_),
    .B(_050_),
    .O(_051_)
  );
  nand_gate _219_ (
    .A(_079_),
    .B(_035_),
    .O(_052_)
  );
  nand_gate _220_ (
    .A(_020_),
    .B(_052_),
    .O(_053_)
  );
  nor_gate _221_ (
    .A(_051_),
    .B(_053_),
    .O(_006_)
  );
  nor_gate _222_ (
    .A(count_reached_in),
    .B(_102_),
    .O(_054_)
  );
  not_gate _223_ (
    .I(_054_),
    .O(_055_)
  );
  nor_gate _224_ (
    .A(curr_state[3]),
    .B(_100_),
    .O(_056_)
  );
  nor_gate _225_ (
    .A(_054_),
    .B(_056_),
    .O(_057_)
  );
  nand_gate _226_ (
    .A(cmd_reg[0]),
    .B(_037_),
    .O(_058_)
  );
  nand_gate _227_ (
    .A(_030_),
    .B(_058_),
    .O(_059_)
  );
  nand_gate _228_ (
    .A(_095_),
    .B(write_shift_register),
    .O(_060_)
  );
  nand_gate _229_ (
    .A(_059_),
    .B(_060_),
    .O(_061_)
  );
  nor_gate _230_ (
    .A(_057_),
    .B(_061_),
    .O(_062_)
  );
  nand_gate _231_ (
    .A(_078_),
    .B(_035_),
    .O(_063_)
  );
  nand_gate _232_ (
    .A(_020_),
    .B(_063_),
    .O(_064_)
  );
  nor_gate _233_ (
    .A(_062_),
    .B(_064_),
    .O(_007_)
  );
  nor_gate _234_ (
    .A(_077_),
    .B(_034_),
    .O(_065_)
  );
  nand_gate _235_ (
    .A(_098_),
    .B(_023_),
    .O(_066_)
  );
  nand_gate _236_ (
    .A(_055_),
    .B(_066_),
    .O(_067_)
  );
  nor_gate _237_ (
    .A(_065_),
    .B(_067_),
    .O(_068_)
  );
  nor_gate _238_ (
    .A(_019_),
    .B(_068_),
    .O(_008_)
  );
  nor_gate _239_ (
    .A(_087_),
    .B(_048_),
    .O(_009_)
  );
  nor_gate _240_ (
    .A(_088_),
    .B(_048_),
    .O(_010_)
  );
  nor_gate _241_ (
    .A(_089_),
    .B(_048_),
    .O(_011_)
  );
  nor_gate _242_ (
    .A(_086_),
    .B(_048_),
    .O(_012_)
  );
  nor_gate _243_ (
    .A(_085_),
    .B(_048_),
    .O(_013_)
  );
  nand_gate _244_ (
    .A(data_in),
    .B(rst_reg[0]),
    .O(_014_)
  );
  nand_gate _245_ (
    .A(rst_reg[1]),
    .B(rst_reg[0]),
    .O(_069_)
  );
  nor_gate _246_ (
    .A(_087_),
    .B(_124_),
    .O(_070_)
  );
  nand_gate _247_ (
    .A(_069_),
    .B(_070_),
    .O(_001_)
  );
  nor_gate _248_ (
    .A(_093_),
    .B(_124_),
    .O(_071_)
  );
  nor_gate _249_ (
    .A(_087_),
    .B(_071_),
    .O(_072_)
  );
  nand_gate _250_ (
    .A(_016_),
    .B(_072_),
    .O(_002_)
  );
  nand_gate _251_ (
    .A(rst_reg[3]),
    .B(_016_),
    .O(_073_)
  );
  nor_gate _252_ (
    .A(_087_),
    .B(_017_),
    .O(_074_)
  );
  nand_gate _253_ (
    .A(_073_),
    .B(_074_),
    .O(_003_)
  );
  nor_gate _254_ (
    .A(_094_),
    .B(_017_),
    .O(_075_)
  );
  nor_gate _255_ (
    .A(_087_),
    .B(_075_),
    .O(_076_)
  );
  nand_gate _256_ (
    .A(_020_),
    .B(_076_),
    .O(_004_)
  );
  (* src = "serial_ctrl.v:177.5-179.8" *)
  dffpq _257_ (
    .CLK(clk),
    .D(curr_state[0]),
    .Q(curr_state_post[0])
  );
  (* src = "serial_ctrl.v:177.5-179.8" *)
  dffpq _258_ (
    .CLK(clk),
    .D(curr_state[1]),
    .Q(curr_state_post[1])
  );
  (* src = "serial_ctrl.v:177.5-179.8" *)
  dffpq _259_ (
    .CLK(clk),
    .D(curr_state[2]),
    .Q(curr_state_post[2])
  );
  (* src = "serial_ctrl.v:177.5-179.8" *)
  dffpq _260_ (
    .CLK(clk),
    .D(curr_state[3]),
    .Q(curr_state_post[3])
  );
  (* src = "serial_ctrl.v:174.5-176.8" *)
  dffnq _261_ (
    .CLK(clk),
    .D(curr_state_pre[0]),
    .Q(curr_state[0])
  );
  (* src = "serial_ctrl.v:174.5-176.8" *)
  dffnq _262_ (
    .CLK(clk),
    .D(curr_state_pre[1]),
    .Q(curr_state[1])
  );
  (* src = "serial_ctrl.v:174.5-176.8" *)
  dffnq _263_ (
    .CLK(clk),
    .D(curr_state_pre[2]),
    .Q(curr_state[2])
  );
  (* src = "serial_ctrl.v:174.5-176.8" *)
  dffnq _264_ (
    .CLK(clk),
    .D(curr_state_pre[3]),
    .Q(curr_state[3])
  );
  (* src = "serial_ctrl.v:110.5-173.8" *)
  dffpq _265_ (
    .CLK(clk),
    .D(_005_),
    .Q(curr_state_pre[0])
  );
  (* src = "serial_ctrl.v:110.5-173.8" *)
  dffpq _266_ (
    .CLK(clk),
    .D(_006_),
    .Q(curr_state_pre[1])
  );
  (* src = "serial_ctrl.v:110.5-173.8" *)
  dffpq _267_ (
    .CLK(clk),
    .D(_007_),
    .Q(curr_state_pre[2])
  );
  (* src = "serial_ctrl.v:110.5-173.8" *)
  dffpq _268_ (
    .CLK(clk),
    .D(_008_),
    .Q(curr_state_pre[3])
  );
  (* src = "serial_ctrl.v:98.5-100.8" *)
  dffnq _269_ (
    .CLK(clk),
    .D(cmd_reg_pre[0]),
    .Q(cmd_reg[0])
  );
  (* src = "serial_ctrl.v:98.5-100.8" *)
  dffnq _270_ (
    .CLK(clk),
    .D(cmd_reg_pre[1]),
    .Q(cmd_reg[1])
  );
  (* src = "serial_ctrl.v:98.5-100.8" *)
  dffnq _271_ (
    .CLK(clk),
    .D(cmd_reg_pre[2]),
    .Q(cmd_reg[2])
  );
  (* src = "serial_ctrl.v:98.5-100.8" *)
  dffnq _272_ (
    .CLK(clk),
    .D(cmd_reg_pre[3]),
    .Q(cmd_reg[3])
  );
  (* src = "serial_ctrl.v:98.5-100.8" *)
  dffnq _273_ (
    .CLK(clk),
    .D(cmd_reg_pre[4]),
    .Q(cmd_reg[4])
  );
  (* src = "serial_ctrl.v:83.5-90.8" *)
  dffpq _274_ (
    .CLK(clk),
    .D(_000_),
    .Q(update)
  );
  (* src = "serial_ctrl.v:101.5-108.8" *)
  dffpq _275_ (
    .CLK(clk),
    .D(_009_),
    .Q(cmd_reg_pre[0])
  );
  (* src = "serial_ctrl.v:101.5-108.8" *)
  dffpq _276_ (
    .CLK(clk),
    .D(_010_),
    .Q(cmd_reg_pre[1])
  );
  (* src = "serial_ctrl.v:101.5-108.8" *)
  dffpq _277_ (
    .CLK(clk),
    .D(_011_),
    .Q(cmd_reg_pre[2])
  );
  (* src = "serial_ctrl.v:101.5-108.8" *)
  dffpq _278_ (
    .CLK(clk),
    .D(_012_),
    .Q(cmd_reg_pre[3])
  );
  (* src = "serial_ctrl.v:101.5-108.8" *)
  dffpq _279_ (
    .CLK(clk),
    .D(_013_),
    .Q(cmd_reg_pre[4])
  );
  (* src = "serial_ctrl.v:27.5-29.8" *)
  dffnq _280_ (
    .CLK(clk),
    .D(rst_reg_pre[0]),
    .Q(rst_reg[0])
  );
  (* src = "serial_ctrl.v:27.5-29.8" *)
  dffnq _281_ (
    .CLK(clk),
    .D(rst_reg_pre[1]),
    .Q(rst_reg[1])
  );
  (* src = "serial_ctrl.v:27.5-29.8" *)
  dffnq _282_ (
    .CLK(clk),
    .D(rst_reg_pre[2]),
    .Q(rst_reg[2])
  );
  (* src = "serial_ctrl.v:27.5-29.8" *)
  dffnq _283_ (
    .CLK(clk),
    .D(rst_reg_pre[3]),
    .Q(rst_reg[3])
  );
  (* src = "serial_ctrl.v:27.5-29.8" *)
  dffnq _284_ (
    .CLK(clk),
    .D(rst_reg_pre[4]),
    .Q(rst_reg[4])
  );
  (* src = "serial_ctrl.v:30.5-37.8" *)
  dffpq _285_ (
    .CLK(clk),
    .D(_014_),
    .Q(rst_reg_pre[0])
  );
  (* src = "serial_ctrl.v:30.5-37.8" *)
  dffpq _286_ (
    .CLK(clk),
    .D(_001_),
    .Q(rst_reg_pre[1])
  );
  (* src = "serial_ctrl.v:30.5-37.8" *)
  dffpq _287_ (
    .CLK(clk),
    .D(_002_),
    .Q(rst_reg_pre[2])
  );
  (* src = "serial_ctrl.v:30.5-37.8" *)
  dffpq _288_ (
    .CLK(clk),
    .D(_003_),
    .Q(rst_reg_pre[3])
  );
  (* src = "serial_ctrl.v:30.5-37.8" *)
  dffpq _289_ (
    .CLK(clk),
    .D(_004_),
    .Q(rst_reg_pre[4])
  );
endmodule

(* top =  1  *)
(* src = "toplevel.v:1.1-56.10" *)
module serial_interface(clk, data_inout, bit_out);
  (* src = "toplevel.v:7.22-7.29" *)
  output [7:0] bit_out;
  (* src = "toplevel.v:4.11-4.14" *)
  input clk;
  (* src = "toplevel.v:10.6-10.19" *)
  wire count_reached;
  (* src = "toplevel.v:5.11-5.21" *)
  inout data_inout;
  (* src = "toplevel.v:18.6-18.14" *)
  wire data_out;
  (* src = "toplevel.v:14.6-14.27" *)
  wire enable_shift_register;
  (* src = "toplevel.v:9.6-9.19" *)
  wire reset_counter;
  (* src = "toplevel.v:13.6-13.26" *)
  wire reset_shift_register;
  (* src = "toplevel.v:12.6-12.12" *)
  wire update;
  (* src = "toplevel.v:24.9-24.14" *)
  wire write;
  (* src = "toplevel.v:36.27-36.47" *)
  wire write_shift_register;
  (* module_not_derived = 32'd1 *)
  (* src = "toplevel.v:21.6-25.2" *)
  tbuf bidir_data_buffer (
    .EN(write),
    .I(data_out),
    .O(data_inout)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "toplevel.v:27.13-37.2" *)
  serial_ctrl control (
    .clk(clk),
    .count_reached_in(count_reached),
    .data_in(data_inout),
    .enable_shift_register(enable_shift_register),
    .reset_count_out(reset_counter),
    .reset_shift_reg_out(reset_shift_register),
    .update(update),
    .write(write),
    .write_shift_register(write_shift_register)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "toplevel.v:39.13-43.2" *)
  bit_counter counter (
    .clk(clk),
    .count_reached_out(count_reached),
    .reset_in(reset_counter)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "toplevel.v:45.16-54.2" *)
  shift_register daisychain (
    .bit_out(bit_out),
    .clk(clk),
    .data_in(data_inout),
    .data_out(data_out),
    .enable(enable_shift_register),
    .reset(reset_shift_register),
    .update(update),
    .write(write_shift_register)
  );
endmodule

(* src = "shift_register.v:2.1-37.10" *)
module shift_register(clk, data_in, update, reset, enable, write, data_out, bit_out);
  (* src = "shift_register.v:11.26-11.33" *)
  output [7:0] bit_out;
  (* src = "shift_register.v:19.20-19.29" *)
  wire [7:0] cells_out;
  (* src = "shift_register.v:4.15-4.18" *)
  input clk;
  (* src = "shift_register.v:5.15-5.22" *)
  input data_in;
  (* src = "shift_register.v:10.16-10.24" *)
  output data_out;
  (* src = "shift_register.v:8.15-8.21" *)
  input enable;
  (* src = "shift_register.v:7.15-7.20" *)
  input reset;
  (* src = "shift_register.v:6.15-6.21" *)
  input update;
  (* src = "shift_register.v:9.15-9.20" *)
  input write;
  (* module_not_derived = 32'd1 *)
  (* src = "shift_register.v:28.19-36.6" *)
  register_cell \regcell[0]  (
    .bit_out(bit_out[0]),
    .chain_in(cells_out[1]),
    .chain_out(data_out),
    .clk(clk),
    .enable(enable),
    .reset(reset),
    .update(update)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "shift_register.v:28.19-36.6" *)
  register_cell \regcell[1]  (
    .bit_out(bit_out[1]),
    .chain_in(cells_out[2]),
    .chain_out(cells_out[1]),
    .clk(clk),
    .enable(enable),
    .reset(reset),
    .update(update)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "shift_register.v:28.19-36.6" *)
  register_cell \regcell[2]  (
    .bit_out(bit_out[2]),
    .chain_in(cells_out[3]),
    .chain_out(cells_out[2]),
    .clk(clk),
    .enable(enable),
    .reset(reset),
    .update(update)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "shift_register.v:28.19-36.6" *)
  register_cell \regcell[3]  (
    .bit_out(bit_out[3]),
    .chain_in(cells_out[4]),
    .chain_out(cells_out[3]),
    .clk(clk),
    .enable(enable),
    .reset(reset),
    .update(update)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "shift_register.v:28.19-36.6" *)
  register_cell \regcell[4]  (
    .bit_out(bit_out[4]),
    .chain_in(cells_out[5]),
    .chain_out(cells_out[4]),
    .clk(clk),
    .enable(enable),
    .reset(reset),
    .update(update)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "shift_register.v:28.19-36.6" *)
  register_cell \regcell[5]  (
    .bit_out(bit_out[5]),
    .chain_in(cells_out[6]),
    .chain_out(cells_out[5]),
    .clk(clk),
    .enable(enable),
    .reset(reset),
    .update(update)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "shift_register.v:28.19-36.6" *)
  register_cell \regcell[6]  (
    .bit_out(bit_out[6]),
    .chain_in(cells_out[7]),
    .chain_out(cells_out[6]),
    .clk(clk),
    .enable(enable),
    .reset(reset),
    .update(update)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "shift_register.v:28.19-36.6" *)
  register_cell \regcell[7]  (
    .bit_out(bit_out[7]),
    .chain_in(data_in),
    .chain_out(cells_out[7]),
    .clk(clk),
    .enable(enable),
    .reset(reset),
    .update(update)
  );
  assign cells_out[0] = data_out;
endmodule
