function layout(toplevel)
    pcell.push_overwrites("stdcells/base", {
                                               pnumtracks = 4,
                                               nnumtracks = 4,
                                               numinnerroutes = 3,
                                               drawtopbotwelltaps = false
                                           })
    local bp = pcell.get_parameters("stdcells/base")
    local cellnames = {
        {
            { instance = "hackfill_1", reference = "isogate" },
            { instance = "_46_", reference = "nand_gate" },
            { instance = "fill_1_9", reference = "isogate" },
            { instance = "fill_1_8", reference = "isogate" },
            { instance = "fill_1_7", reference = "isogate" },
            { instance = "fill_1_6", reference = "isogate" },
            { instance = "fill_1_5", reference = "isogate" },
            { instance = "fill_1_4", reference = "isogate" },
            { instance = "fill_1_3", reference = "isogate" },
            { instance = "fill_1_2", reference = "isogate" },
            { instance = "fill_1_1", reference = "isogate" },
            { instance = "_53_", reference = "and_gate" },
            { instance = "fill_1_18", reference = "isogate" },
            { instance = "fill_1_17", reference = "isogate" },
            { instance = "fill_1_16", reference = "isogate" },
            { instance = "fill_1_15", reference = "isogate" },
            { instance = "fill_1_14", reference = "isogate" },
            { instance = "fill_1_13", reference = "isogate" },
            { instance = "fill_1_12", reference = "isogate" },
            { instance = "fill_1_11", reference = "isogate" },
            { instance = "fill_1_10", reference = "isogate" },
            { instance = "_08_reg", reference = "and_gate" },
            { instance = "fill_1_27", reference = "isogate" },
            { instance = "fill_1_26", reference = "isogate" },
            { instance = "fill_1_25", reference = "isogate" },
            { instance = "fill_1_24", reference = "isogate" },
            { instance = "fill_1_23", reference = "isogate" },
            { instance = "fill_1_22", reference = "isogate" },
            { instance = "fill_1_21", reference = "isogate" },
            { instance = "fill_1_20", reference = "isogate" },
            { instance = "fill_1_19", reference = "isogate" },
            { instance = "_57_", reference = "nand_gate" },
            { instance = "fill_1_36", reference = "isogate" },
            { instance = "fill_1_35", reference = "isogate" },
            { instance = "fill_1_34", reference = "isogate" },
            { instance = "fill_1_33", reference = "isogate" },
            { instance = "fill_1_32", reference = "isogate" },
            { instance = "fill_1_31", reference = "isogate" },
            { instance = "fill_1_30", reference = "isogate" },
            { instance = "fill_1_29", reference = "isogate" },
            { instance = "fill_1_28", reference = "isogate" },
            { instance = "_71_", reference = "dffnq" },
            { instance = "fill_1_44", reference = "isogate" },
            { instance = "fill_1_43", reference = "isogate" },
            { instance = "fill_1_42", reference = "isogate" },
            { instance = "fill_1_41", reference = "isogate" },
            { instance = "fill_1_40", reference = "isogate" },
            { instance = "fill_1_39", reference = "isogate" },
            { instance = "fill_1_38", reference = "isogate" },
            { instance = "fill_1_37", reference = "isogate" },
            { instance = "_05_reg", reference = "nor_gate" },
            { instance = "fill_1_52", reference = "isogate" },
            { instance = "fill_1_51", reference = "isogate" },
            { instance = "fill_1_50", reference = "isogate" },
            { instance = "fill_1_49", reference = "isogate" },
            { instance = "fill_1_48", reference = "isogate" },
            { instance = "fill_1_47", reference = "isogate" },
            { instance = "fill_1_46", reference = "isogate" },
            { instance = "fill_1_45", reference = "isogate" },
            { instance = "_07_reg", reference = "nor_gate" },
            { instance = "fill_1_60", reference = "isogate" },
            { instance = "fill_1_59", reference = "isogate" },
            { instance = "fill_1_58", reference = "isogate" },
            { instance = "fill_1_57", reference = "isogate" },
            { instance = "fill_1_56", reference = "isogate" },
            { instance = "fill_1_55", reference = "isogate" },
            { instance = "fill_1_54", reference = "isogate" },
            { instance = "fill_1_53", reference = "isogate" },
            { instance = "_69_", reference = "dffnq" },
            { instance = "fill_1_68", reference = "isogate" },
            { instance = "fill_1_67", reference = "isogate" },
            { instance = "fill_1_66", reference = "isogate" },
            { instance = "fill_1_65", reference = "isogate" },
            { instance = "fill_1_64", reference = "isogate" },
            { instance = "fill_1_63", reference = "isogate" },
            { instance = "fill_1_62", reference = "isogate" },
            { instance = "fill_1_61", reference = "isogate" },
            { instance = "_10_reg", reference = "nor_gate" },
        },
        {
            { instance = "hackfill_2", reference = "isogate" },
            { instance = "_55_", reference = "nand_gate" },
            { instance = "fill_2_5", reference = "isogate" },
            { instance = "fill_2_4", reference = "isogate" },
            { instance = "fill_2_3", reference = "isogate" },
            { instance = "fill_2_2", reference = "isogate" },
            { instance = "fill_2_1", reference = "isogate" },
            { instance = "_52_", reference = "nand_gate" },
            { instance = "fill_2_10", reference = "isogate" },
            { instance = "fill_2_9", reference = "isogate" },
            { instance = "fill_2_8", reference = "isogate" },
            { instance = "fill_2_7", reference = "isogate" },
            { instance = "fill_2_6", reference = "isogate" },
            { instance = "_34_", reference = "and_gate" },
            { instance = "fill_2_15", reference = "isogate" },
            { instance = "fill_2_14", reference = "isogate" },
            { instance = "fill_2_13", reference = "isogate" },
            { instance = "fill_2_12", reference = "isogate" },
            { instance = "fill_2_11", reference = "isogate" },
            { instance = "_48_", reference = "nand_gate" },
            { instance = "fill_2_20", reference = "isogate" },
            { instance = "fill_2_19", reference = "isogate" },
            { instance = "fill_2_18", reference = "isogate" },
            { instance = "fill_2_17", reference = "isogate" },
            { instance = "fill_2_16", reference = "isogate" },
            { instance = "_49_", reference = "and_gate" },
            { instance = "fill_2_25", reference = "isogate" },
            { instance = "fill_2_24", reference = "isogate" },
            { instance = "fill_2_23", reference = "isogate" },
            { instance = "fill_2_22", reference = "isogate" },
            { instance = "fill_2_21", reference = "isogate" },
            { instance = "_40_", reference = "and_gate" },
            { instance = "fill_2_30", reference = "isogate" },
            { instance = "fill_2_29", reference = "isogate" },
            { instance = "fill_2_28", reference = "isogate" },
            { instance = "fill_2_27", reference = "isogate" },
            { instance = "fill_2_26", reference = "isogate" },
            { instance = "_68_", reference = "dffpq" },
            { instance = "fill_2_35", reference = "isogate" },
            { instance = "fill_2_34", reference = "isogate" },
            { instance = "fill_2_33", reference = "isogate" },
            { instance = "fill_2_32", reference = "isogate" },
            { instance = "fill_2_31", reference = "isogate" },
            { instance = "_44_", reference = "nand_gate" },
            { instance = "fill_2_40", reference = "isogate" },
            { instance = "fill_2_39", reference = "isogate" },
            { instance = "fill_2_38", reference = "isogate" },
            { instance = "fill_2_37", reference = "isogate" },
            { instance = "fill_2_36", reference = "isogate" },
            { instance = "_19_reg", reference = "dffnq" },
            { instance = "fill_2_45", reference = "isogate" },
            { instance = "fill_2_44", reference = "isogate" },
            { instance = "fill_2_43", reference = "isogate" },
            { instance = "fill_2_42", reference = "isogate" },
            { instance = "fill_2_41", reference = "isogate" },
            { instance = "_43_", reference = "and_gate" },
            { instance = "fill_2_50", reference = "isogate" },
            { instance = "fill_2_49", reference = "isogate" },
            { instance = "fill_2_48", reference = "isogate" },
            { instance = "fill_2_47", reference = "isogate" },
            { instance = "fill_2_46", reference = "isogate" },
            { instance = "_39_", reference = "and_gate" },
            { instance = "fill_2_54", reference = "isogate" },
            { instance = "fill_2_53", reference = "isogate" },
            { instance = "fill_2_52", reference = "isogate" },
            { instance = "fill_2_51", reference = "isogate" },
            { instance = "_30_", reference = "not_gate" },
        },
        {
            { instance = "hackfill_3", reference = "isogate" },
            { instance = "_42_", reference = "and_gate" },
            { instance = "fill_3_8", reference = "isogate" },
            { instance = "fill_3_7", reference = "isogate" },
            { instance = "fill_3_6", reference = "isogate" },
            { instance = "fill_3_5", reference = "isogate" },
            { instance = "fill_3_4", reference = "isogate" },
            { instance = "fill_3_3", reference = "isogate" },
            { instance = "fill_3_2", reference = "isogate" },
            { instance = "fill_3_1", reference = "isogate" },
            { instance = "_50_", reference = "xor_gate" },
            { instance = "fill_3_16", reference = "isogate" },
            { instance = "fill_3_15", reference = "isogate" },
            { instance = "fill_3_14", reference = "isogate" },
            { instance = "fill_3_13", reference = "isogate" },
            { instance = "fill_3_12", reference = "isogate" },
            { instance = "fill_3_11", reference = "isogate" },
            { instance = "fill_3_10", reference = "isogate" },
            { instance = "fill_3_9", reference = "isogate" },
            { instance = "_20_reg", reference = "dffnq" },
            { instance = "fill_3_24", reference = "isogate" },
            { instance = "fill_3_23", reference = "isogate" },
            { instance = "fill_3_22", reference = "isogate" },
            { instance = "fill_3_21", reference = "isogate" },
            { instance = "fill_3_20", reference = "isogate" },
            { instance = "fill_3_19", reference = "isogate" },
            { instance = "fill_3_18", reference = "isogate" },
            { instance = "fill_3_17", reference = "isogate" },
            { instance = "_35_", reference = "nand_gate" },
            { instance = "fill_3_32", reference = "isogate" },
            { instance = "fill_3_31", reference = "isogate" },
            { instance = "fill_3_30", reference = "isogate" },
            { instance = "fill_3_29", reference = "isogate" },
            { instance = "fill_3_28", reference = "isogate" },
            { instance = "fill_3_27", reference = "isogate" },
            { instance = "fill_3_26", reference = "isogate" },
            { instance = "fill_3_25", reference = "isogate" },
            { instance = "_21_reg", reference = "dffnq" },
            { instance = "fill_3_40", reference = "isogate" },
            { instance = "fill_3_39", reference = "isogate" },
            { instance = "fill_3_38", reference = "isogate" },
            { instance = "fill_3_37", reference = "isogate" },
            { instance = "fill_3_36", reference = "isogate" },
            { instance = "fill_3_35", reference = "isogate" },
            { instance = "fill_3_34", reference = "isogate" },
            { instance = "fill_3_33", reference = "isogate" },
            { instance = "_11_reg", reference = "and_gate" },
            { instance = "fill_3_47", reference = "isogate" },
            { instance = "fill_3_46", reference = "isogate" },
            { instance = "fill_3_45", reference = "isogate" },
            { instance = "fill_3_44", reference = "isogate" },
            { instance = "fill_3_43", reference = "isogate" },
            { instance = "fill_3_42", reference = "isogate" },
            { instance = "fill_3_41", reference = "isogate" },
            { instance = "_15_reg", reference = "dffpq" },
        },
        {
            { instance = "hackfill_4", reference = "isogate" },
            { instance = "_37_", reference = "and_gate" },
            { instance = "fill_4_14", reference = "isogate" },
            { instance = "fill_4_13", reference = "isogate" },
            { instance = "fill_4_12", reference = "isogate" },
            { instance = "fill_4_11", reference = "isogate" },
            { instance = "fill_4_10", reference = "isogate" },
            { instance = "fill_4_9", reference = "isogate" },
            { instance = "fill_4_8", reference = "isogate" },
            { instance = "fill_4_7", reference = "isogate" },
            { instance = "fill_4_6", reference = "isogate" },
            { instance = "fill_4_5", reference = "isogate" },
            { instance = "fill_4_4", reference = "isogate" },
            { instance = "fill_4_3", reference = "isogate" },
            { instance = "fill_4_2", reference = "isogate" },
            { instance = "fill_4_1", reference = "isogate" },
            { instance = "_63_", reference = "and_gate" },
            { instance = "fill_4_28", reference = "isogate" },
            { instance = "fill_4_27", reference = "isogate" },
            { instance = "fill_4_26", reference = "isogate" },
            { instance = "fill_4_25", reference = "isogate" },
            { instance = "fill_4_24", reference = "isogate" },
            { instance = "fill_4_23", reference = "isogate" },
            { instance = "fill_4_22", reference = "isogate" },
            { instance = "fill_4_21", reference = "isogate" },
            { instance = "fill_4_20", reference = "isogate" },
            { instance = "fill_4_19", reference = "isogate" },
            { instance = "fill_4_18", reference = "isogate" },
            { instance = "fill_4_17", reference = "isogate" },
            { instance = "fill_4_16", reference = "isogate" },
            { instance = "fill_4_15", reference = "isogate" },
            { instance = "_65_", reference = "buf_gate" },
            { instance = "fill_4_42", reference = "isogate" },
            { instance = "fill_4_41", reference = "isogate" },
            { instance = "fill_4_40", reference = "isogate" },
            { instance = "fill_4_39", reference = "isogate" },
            { instance = "fill_4_38", reference = "isogate" },
            { instance = "fill_4_37", reference = "isogate" },
            { instance = "fill_4_36", reference = "isogate" },
            { instance = "fill_4_35", reference = "isogate" },
            { instance = "fill_4_34", reference = "isogate" },
            { instance = "fill_4_33", reference = "isogate" },
            { instance = "fill_4_32", reference = "isogate" },
            { instance = "fill_4_31", reference = "isogate" },
            { instance = "fill_4_30", reference = "isogate" },
            { instance = "fill_4_29", reference = "isogate" },
            { instance = "_59_", reference = "nand_gate" },
            { instance = "fill_4_56", reference = "isogate" },
            { instance = "fill_4_55", reference = "isogate" },
            { instance = "fill_4_54", reference = "isogate" },
            { instance = "fill_4_53", reference = "isogate" },
            { instance = "fill_4_52", reference = "isogate" },
            { instance = "fill_4_51", reference = "isogate" },
            { instance = "fill_4_50", reference = "isogate" },
            { instance = "fill_4_49", reference = "isogate" },
            { instance = "fill_4_48", reference = "isogate" },
            { instance = "fill_4_47", reference = "isogate" },
            { instance = "fill_4_46", reference = "isogate" },
            { instance = "fill_4_45", reference = "isogate" },
            { instance = "fill_4_44", reference = "isogate" },
            { instance = "fill_4_43", reference = "isogate" },
            { instance = "_36_", reference = "xor_gate" },
            { instance = "fill_4_70", reference = "isogate" },
            { instance = "fill_4_69", reference = "isogate" },
            { instance = "fill_4_68", reference = "isogate" },
            { instance = "fill_4_67", reference = "isogate" },
            { instance = "fill_4_66", reference = "isogate" },
            { instance = "fill_4_65", reference = "isogate" },
            { instance = "fill_4_64", reference = "isogate" },
            { instance = "fill_4_63", reference = "isogate" },
            { instance = "fill_4_62", reference = "isogate" },
            { instance = "fill_4_61", reference = "isogate" },
            { instance = "fill_4_60", reference = "isogate" },
            { instance = "fill_4_59", reference = "isogate" },
            { instance = "fill_4_58", reference = "isogate" },
            { instance = "fill_4_57", reference = "isogate" },
            { instance = "_31_", reference = "not_gate" },
            { instance = "fill_4_84", reference = "isogate" },
            { instance = "fill_4_83", reference = "isogate" },
            { instance = "fill_4_82", reference = "isogate" },
            { instance = "fill_4_81", reference = "isogate" },
            { instance = "fill_4_80", reference = "isogate" },
            { instance = "fill_4_79", reference = "isogate" },
            { instance = "fill_4_78", reference = "isogate" },
            { instance = "fill_4_77", reference = "isogate" },
            { instance = "fill_4_76", reference = "isogate" },
            { instance = "fill_4_75", reference = "isogate" },
            { instance = "fill_4_74", reference = "isogate" },
            { instance = "fill_4_73", reference = "isogate" },
            { instance = "fill_4_72", reference = "isogate" },
            { instance = "fill_4_71", reference = "isogate" },
            { instance = "_06_reg", reference = "or_gate" },
            { instance = "fill_4_97", reference = "isogate" },
            { instance = "fill_4_96", reference = "isogate" },
            { instance = "fill_4_95", reference = "isogate" },
            { instance = "fill_4_94", reference = "isogate" },
            { instance = "fill_4_93", reference = "isogate" },
            { instance = "fill_4_92", reference = "isogate" },
            { instance = "fill_4_91", reference = "isogate" },
            { instance = "fill_4_90", reference = "isogate" },
            { instance = "fill_4_89", reference = "isogate" },
            { instance = "fill_4_88", reference = "isogate" },
            { instance = "fill_4_87", reference = "isogate" },
            { instance = "fill_4_86", reference = "isogate" },
            { instance = "fill_4_85", reference = "isogate" },
            { instance = "_33_", reference = "and_gate" },
        },
        {
            { instance = "hackfill_5", reference = "isogate" },
            { instance = "_64_", reference = "nand_gate" },
            { instance = "fill_5_2", reference = "isogate" },
            { instance = "fill_5_1", reference = "isogate" },
            { instance = "_51_", reference = "nand_gate" },
            { instance = "fill_5_3", reference = "isogate" },
            { instance = "_45_", reference = "nand_gate" },
            { instance = "fill_5_4", reference = "isogate" },
            { instance = "_62_", reference = "and_gate" },
            { instance = "fill_5_5", reference = "isogate" },
            { instance = "_60_", reference = "nand_gate" },
            { instance = "fill_5_6", reference = "isogate" },
            { instance = "_73_", reference = "dffpq" },
            { instance = "fill_5_7", reference = "isogate" },
            { instance = "_14_reg", reference = "dffpq" },
            { instance = "fill_5_8", reference = "isogate" },
            { instance = "_70_", reference = "dffnq" },
            { instance = "fill_5_9", reference = "isogate" },
            { instance = "_13_reg", reference = "dffpq" },
            { instance = "fill_5_10", reference = "isogate" },
            { instance = "_16_reg", reference = "dffpq" },
        },
        {
            { instance = "hackfill_6", reference = "isogate" },
            { instance = "_29_", reference = "not_gate" },
            { instance = "fill_6_8", reference = "isogate" },
            { instance = "fill_6_7", reference = "isogate" },
            { instance = "fill_6_6", reference = "isogate" },
            { instance = "fill_6_5", reference = "isogate" },
            { instance = "fill_6_4", reference = "isogate" },
            { instance = "fill_6_3", reference = "isogate" },
            { instance = "fill_6_2", reference = "isogate" },
            { instance = "fill_6_1", reference = "isogate" },
            { instance = "_38_", reference = "nor_gate" },
            { instance = "fill_6_16", reference = "isogate" },
            { instance = "fill_6_15", reference = "isogate" },
            { instance = "fill_6_14", reference = "isogate" },
            { instance = "fill_6_13", reference = "isogate" },
            { instance = "fill_6_12", reference = "isogate" },
            { instance = "fill_6_11", reference = "isogate" },
            { instance = "fill_6_10", reference = "isogate" },
            { instance = "fill_6_9", reference = "isogate" },
            { instance = "_41_", reference = "nor_gate" },
            { instance = "fill_6_24", reference = "isogate" },
            { instance = "fill_6_23", reference = "isogate" },
            { instance = "fill_6_22", reference = "isogate" },
            { instance = "fill_6_21", reference = "isogate" },
            { instance = "fill_6_20", reference = "isogate" },
            { instance = "fill_6_19", reference = "isogate" },
            { instance = "fill_6_18", reference = "isogate" },
            { instance = "fill_6_17", reference = "isogate" },
            { instance = "_58_", reference = "and_gate" },
            { instance = "fill_6_32", reference = "isogate" },
            { instance = "fill_6_31", reference = "isogate" },
            { instance = "fill_6_30", reference = "isogate" },
            { instance = "fill_6_29", reference = "isogate" },
            { instance = "fill_6_28", reference = "isogate" },
            { instance = "fill_6_27", reference = "isogate" },
            { instance = "fill_6_26", reference = "isogate" },
            { instance = "fill_6_25", reference = "isogate" },
            { instance = "_66_", reference = "dffpq" },
            { instance = "fill_6_40", reference = "isogate" },
            { instance = "fill_6_39", reference = "isogate" },
            { instance = "fill_6_38", reference = "isogate" },
            { instance = "fill_6_37", reference = "isogate" },
            { instance = "fill_6_36", reference = "isogate" },
            { instance = "fill_6_35", reference = "isogate" },
            { instance = "fill_6_34", reference = "isogate" },
            { instance = "fill_6_33", reference = "isogate" },
            { instance = "_32_", reference = "not_gate" },
            { instance = "fill_6_48", reference = "isogate" },
            { instance = "fill_6_47", reference = "isogate" },
            { instance = "fill_6_46", reference = "isogate" },
            { instance = "fill_6_45", reference = "isogate" },
            { instance = "fill_6_44", reference = "isogate" },
            { instance = "fill_6_43", reference = "isogate" },
            { instance = "fill_6_42", reference = "isogate" },
            { instance = "fill_6_41", reference = "isogate" },
            { instance = "_18_reg", reference = "dffnq" },
            { instance = "fill_6_56", reference = "isogate" },
            { instance = "fill_6_55", reference = "isogate" },
            { instance = "fill_6_54", reference = "isogate" },
            { instance = "fill_6_53", reference = "isogate" },
            { instance = "fill_6_52", reference = "isogate" },
            { instance = "fill_6_51", reference = "isogate" },
            { instance = "fill_6_50", reference = "isogate" },
            { instance = "fill_6_49", reference = "isogate" },
            { instance = "_12_reg", reference = "dffpq" },
        },
        {
            { instance = "hackfill_7", reference = "isogate" },
            { instance = "_54_", reference = "nand_gate" },
            { instance = "fill_7_8", reference = "isogate" },
            { instance = "fill_7_7", reference = "isogate" },
            { instance = "fill_7_6", reference = "isogate" },
            { instance = "fill_7_5", reference = "isogate" },
            { instance = "fill_7_4", reference = "isogate" },
            { instance = "fill_7_3", reference = "isogate" },
            { instance = "fill_7_2", reference = "isogate" },
            { instance = "fill_7_1", reference = "isogate" },
            { instance = "_56_", reference = "and_gate" },
            { instance = "fill_7_16", reference = "isogate" },
            { instance = "fill_7_15", reference = "isogate" },
            { instance = "fill_7_14", reference = "isogate" },
            { instance = "fill_7_13", reference = "isogate" },
            { instance = "fill_7_12", reference = "isogate" },
            { instance = "fill_7_11", reference = "isogate" },
            { instance = "fill_7_10", reference = "isogate" },
            { instance = "fill_7_9", reference = "isogate" },
            { instance = "_61_", reference = "nand_gate" },
            { instance = "fill_7_24", reference = "isogate" },
            { instance = "fill_7_23", reference = "isogate" },
            { instance = "fill_7_22", reference = "isogate" },
            { instance = "fill_7_21", reference = "isogate" },
            { instance = "fill_7_20", reference = "isogate" },
            { instance = "fill_7_19", reference = "isogate" },
            { instance = "fill_7_18", reference = "isogate" },
            { instance = "fill_7_17", reference = "isogate" },
            { instance = "_47_", reference = "nor_gate" },
            { instance = "fill_7_32", reference = "isogate" },
            { instance = "fill_7_31", reference = "isogate" },
            { instance = "fill_7_30", reference = "isogate" },
            { instance = "fill_7_29", reference = "isogate" },
            { instance = "fill_7_28", reference = "isogate" },
            { instance = "fill_7_27", reference = "isogate" },
            { instance = "fill_7_26", reference = "isogate" },
            { instance = "fill_7_25", reference = "isogate" },
            { instance = "_67_", reference = "dffpq" },
            { instance = "fill_7_40", reference = "isogate" },
            { instance = "fill_7_39", reference = "isogate" },
            { instance = "fill_7_38", reference = "isogate" },
            { instance = "fill_7_37", reference = "isogate" },
            { instance = "fill_7_36", reference = "isogate" },
            { instance = "fill_7_35", reference = "isogate" },
            { instance = "fill_7_34", reference = "isogate" },
            { instance = "fill_7_33", reference = "isogate" },
            { instance = "_09_reg", reference = "nand_gate" },
            { instance = "fill_7_47", reference = "isogate" },
            { instance = "fill_7_46", reference = "isogate" },
            { instance = "fill_7_45", reference = "isogate" },
            { instance = "fill_7_44", reference = "isogate" },
            { instance = "fill_7_43", reference = "isogate" },
            { instance = "fill_7_42", reference = "isogate" },
            { instance = "fill_7_41", reference = "isogate" },
            { instance = "_17_reg", reference = "dffnq" },
            { instance = "fill_7_54", reference = "isogate" },
            { instance = "fill_7_53", reference = "isogate" },
            { instance = "fill_7_52", reference = "isogate" },
            { instance = "fill_7_51", reference = "isogate" },
            { instance = "fill_7_50", reference = "isogate" },
            { instance = "fill_7_49", reference = "isogate" },
            { instance = "fill_7_48", reference = "isogate" },
            { instance = "_72_", reference = "dffnq" },
        },
    }
    local xpitch = bp.gspace + bp.glength
    local rows = placement.create_reference_rows(cellnames, xpitch)
    local cells = placement.rowwise(toplevel, rows)
    local routes = {
        {
            name = "curr_state_3",
            { nodraw = true, where = cells["_38_"]:get_anchor("A"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -10, type = "delta" },
            { y = -1, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { nodraw = true, where = cells["_72_"]:get_anchor("Q"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = -10, type = "delta" },
            { x = -116, type = "delta" },
            { y = -1, type = "delta" },
            { x = -10, type = "delta" },
        },
        {
            name = "_01_",
            { nodraw = true, where = cells["_49_"]:get_anchor("A"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = 1, type = "delta" },
            { x = -9, type = "delta" },
            { y = -1, type = "delta" },
            { x = -9, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { nodraw = true, where = cells["_29_"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = 8, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -47, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 7, type = "delta" },
        },
        {
            name = "curr_state_1",
            { nodraw = true, where = cells["_33_"]:get_anchor("A"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = -25, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 3, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { nodraw = true, where = cells["_70_"]:get_anchor("Q"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = -2, type = "delta" },
            { x = 42, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -9, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_36_"]:get_anchor("A"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = 9, type = "delta" },
            { x = 17, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_41_"]:get_anchor("A"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = -15, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 52, type = "delta" },
        },
        {
            name = "_02_",
            { nodraw = true, where = cells["_30_"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = 1, type = "delta" },
            { x = -10, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "curr_state_0",
            { nodraw = true, where = cells["_40_"]:get_anchor("A"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = -11, type = "delta" },
            { x = 67, type = "delta" },
            { y = -1, type = "delta" },
            { x = 11, type = "delta" },
            { y = -1, type = "delta" },
            { x = 3, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { nodraw = true, where = cells["_36_"]:get_anchor("B"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = -33, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_31_"]:get_anchor("I"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = -2, type = "delta" },
            { x = -25, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -3, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_41_"]:get_anchor("B"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = -1, type = "delta" },
            { x = 51, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -23, type = "delta" },
        },
        {
            name = "_03_",
            { nodraw = true, where = cells["_33_"]:get_anchor("B"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -16, type = "delta" },
            { y = 1, type = "delta" },
            { x = -18, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { nodraw = true, where = cells["_45_"]:get_anchor("A"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = 3, type = "delta" },
            { x = 90, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -14, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 6, type = "delta" },
        },
        {
            name = "command_1",
            { nodraw = true, where = cells["_32_"]:get_anchor("I"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = -61, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 7, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { nodraw = true, where = cells["_18_reg"]:get_anchor("Q"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = -2, type = "delta" },
            { x = -31, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { z = -1, nodraw = true, type = "via" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_50_"]:get_anchor("A"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = -1, type = "delta" },
            { x = 62, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { z = -1, nodraw = true, type = "via" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_14_reg"]:get_anchor("D"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = -27, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_04_",
            { nodraw = true, where = cells["_32_"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = -1, type = "delta" },
            { x = -2, type = "delta" },
            { y = -2, type = "delta" },
            { x = -53, type = "delta" },
            { y = 3, type = "delta" },
            { x = 1, type = "delta" },
            { y = 1, type = "delta" },
            { x = 2, type = "delta" },
            { y = -2, type = "delta" },
            { x = 9, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_05_",
            { nodraw = true, where = cells["_33_"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -11, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -23, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = -9, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { nodraw = true, where = cells["_35_"]:get_anchor("A"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = 3, type = "delta" },
            { x = 63, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -3, type = "delta" },
        },
        {
            name = "curr_state_2",
            { nodraw = true, where = cells["_34_"]:get_anchor("B"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = -13, type = "delta" },
            { x = 54, type = "delta" },
            { y = 2, type = "delta" },
            { x = 2, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { nodraw = true, where = cells["_38_"]:get_anchor("B"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = -49, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 6, type = "delta" },
        },
        {
            name = "_06_",
            { nodraw = true, where = cells["_34_"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -4, type = "delta" },
            { y = -1, type = "delta" },
            { x = -6, type = "delta" },
            { y = -1, type = "delta" },
            { x = -2, type = "delta" },
            { y = 2, type = "delta" },
            { x = -1, type = "delta" },
            { y = 1, type = "delta" },
            { x = -7, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { nodraw = true, where = cells["_37_"]:get_anchor("A"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = -24, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 3, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_61_"]:get_anchor("A"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = -1, type = "delta" },
            { x = -24, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -33, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_35_"]:get_anchor("B"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = -10, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = -39, type = "delta" },
            { y = -1, type = "delta" },
            { x = -17, type = "delta" },
            { y = -1, type = "delta" },
        },
        {
            name = "_07_",
            { nodraw = true, where = cells["_36_"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = -3, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = -12, type = "delta" },
            { y = 1, type = "delta" },
            { x = -53, type = "delta" },
            { y = 1, type = "delta" },
            { x = -18, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_08_",
            { nodraw = true, where = cells["_42_"]:get_anchor("A"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -1, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -24, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 1, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { nodraw = true, where = cells["_38_"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -2, type = "delta" },
            { y = -1, type = "delta" },
            { x = -11, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -36, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_43_"]:get_anchor("B"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = 1, type = "delta" },
            { x = -2, type = "delta" },
            { y = 4, type = "delta" },
            { x = -116, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { z = -1, nodraw = true, type = "via" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_39_"]:get_anchor("B"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -10, type = "delta" },
        },
        {
            name = "enable_data_counter",
            { nodraw = true, where = cells["_39_"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = -2, type = "delta" },
            { x = -78, type = "delta" },
            { y = 1, type = "delta" },
            { x = -7, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "write",
            { nodraw = true, where = cells["_40_"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = 2, type = "delta" },
            { x = -5, type = "delta" },
            { y = -1, type = "delta" },
            { x = -6, type = "delta" },
            { y = -1, type = "delta" },
            { x = -3, type = "delta" },
            { y = -1, type = "delta" },
            { x = -7, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_09_",
            { nodraw = true, where = cells["_42_"]:get_anchor("B"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = 1, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -24, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 11, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { nodraw = true, where = cells["_54_"]:get_anchor("B"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = 1, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -48, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_47_"]:get_anchor("A"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = -2, type = "delta" },
            { x = -33, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { z = -1, nodraw = true, type = "via" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_41_"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = 9, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = -11, type = "delta" },
        },
        {
            name = "write_shift_register",
            { nodraw = true, where = cells["_60_"]:get_anchor("B"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -3, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -25, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = -13, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "receive_command",
            { nodraw = true, where = cells["_59_"]:get_anchor("A"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -34, type = "delta" },
            { y = -1, type = "delta" },
            { x = -14, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -23, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { z = -1, nodraw = false, type = "via" },
            { nodraw = true, where = cells["_11_reg"]:get_anchor("B"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -24, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { x = -3, type = "delta" },
            { y = 11, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = -5, type = "delta" },
            { y = 1, type = "delta" },
            { x = -16, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_43_"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -2, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { x = -1, type = "delta" },
            { y = 12, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = -4, type = "delta" },
            { y = 1, type = "delta" },
            { x = -9, type = "delta" },
        },
        {
            name = "command_ready",
            { nodraw = true, where = cells["_44_"]:get_anchor("A"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = -15, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 42, type = "delta" },
            { y = 1, type = "delta" },
            { x = 3, type = "delta" },
            { y = 1, type = "delta" },
            { x = 10, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { nodraw = true, where = cells["_51_"]:get_anchor("A"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = 4, type = "delta" },
            { x = 76, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -38, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_58_"]:get_anchor("A"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = -10, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = -5, type = "delta" },
        },
        {
            name = "command_0",
            { nodraw = true, where = cells["_44_"]:get_anchor("B"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = -10, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 1, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { nodraw = true, where = cells["_17_reg"]:get_anchor("Q"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = -2, type = "delta" },
            { x = -25, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -59, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_13_reg"]:get_anchor("D"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { x = -10, type = "delta" },
            { y = -2, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_50_"]:get_anchor("B"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = 2, type = "delta" },
            { x = 69, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
        },
        {
            name = "_10_",
            { nodraw = true, where = cells["_45_"]:get_anchor("B"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = -4, type = "delta" },
            { x = 51, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -34, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 15, type = "delta" },
            { y = 1, type = "delta" },
            { x = 7, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_11_",
            { nodraw = true, where = cells["_45_"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = 1, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -46, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = -11, type = "delta" },
            { y = -1, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_12_",
            { nodraw = true, where = cells["_47_"]:get_anchor("B"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = 1, type = "delta" },
            { x = -21, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -74, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = -13, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_28__0",
            { nodraw = true, where = cells["_47_"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = 8, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -13, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "data_ready",
            { nodraw = true, where = cells["_60_"]:get_anchor("A"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = 3, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -35, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 4, type = "delta" },
            { y = 1, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_13_",
            { nodraw = true, where = cells["_49_"]:get_anchor("B"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = -1, type = "delta" },
            { x = -2, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = 2, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = -5, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_14_",
            { nodraw = true, where = cells["_49_"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = -13, type = "delta" },
            { x = 2, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { nodraw = true, where = cells["_64_"]:get_anchor("A"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = -3, type = "delta" },
            { x = 38, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -32, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_15_",
            { nodraw = true, where = cells["_51_"]:get_anchor("B"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = -3, type = "delta" },
            { x = -2, type = "delta" },
            { y = 6, type = "delta" },
            { x = 19, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -28, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 1, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_16_",
            { nodraw = true, where = cells["_51_"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = -36, type = "delta" },
            { x = 2, type = "delta" },
            { y = -1, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_17_",
            { nodraw = true, where = cells["_56_"]:get_anchor("A"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -1, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -59, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "command_empty",
            { nodraw = true, where = cells["_08_reg"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -12, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { x = -2, type = "delta" },
            { y = -1, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = -4, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { nodraw = true, where = cells["_54_"]:get_anchor("A"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = 3, type = "delta" },
            { y = 1, type = "delta" },
            { x = 9, type = "delta" },
            { y = -1, type = "delta" },
            { x = 4, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -71, type = "delta" },
        },
        {
            name = "_18_",
            { nodraw = true, where = cells["_55_"]:get_anchor("B"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = -8, type = "delta" },
            { x = 12, type = "delta" },
            { y = -1, type = "delta" },
            { x = 1, type = "delta" },
            { y = -1, type = "delta" },
            { x = 2, type = "delta" },
            { y = -1, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_19_",
            { nodraw = true, where = cells["_61_"]:get_anchor("B"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -11, type = "delta" },
            { y = 1, type = "delta" },
            { x = -14, type = "delta" },
            { y = -2, type = "delta" },
            { x = 2, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_20_",
            { nodraw = true, where = cells["_56_"]:get_anchor("B"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -6, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -61, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = -4, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_21_",
            { nodraw = true, where = cells["_56_"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = 10, type = "delta" },
            { y = -1, type = "delta" },
            { x = 2, type = "delta" },
            { y = 1, type = "delta" },
            { x = 9, type = "delta" },
            { y = -1, type = "delta" },
            { x = 3, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -70, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 2, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_28__1",
            { nodraw = true, where = cells["_67_"]:get_anchor("D"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = -15, type = "delta" },
            { x = -1, type = "delta" },
            { y = -58, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = -3, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_22_",
            { nodraw = true, where = cells["_58_"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = -25, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 21, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_23_",
            { nodraw = true, where = cells["_59_"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = 2, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = -37, type = "delta" },
            { y = -1, type = "delta" },
            { x = -2, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_24_",
            { nodraw = true, where = cells["_60_"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -3, type = "delta" },
            { y = -1, type = "delta" },
            { x = -5, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_25_",
            { nodraw = true, where = cells["_61_"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { x = -10, type = "delta" },
            { y = 3, type = "delta" },
            { x = -2, type = "delta" },
            { y = -26, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_26_",
            { nodraw = true, where = cells["_62_"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -3, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { x = 6, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { y = -13, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_27_",
            { nodraw = true, where = cells["_64_"]:get_anchor("B"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = 4, type = "delta" },
            { x = 23, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -17, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = -1, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_28__2",
            { nodraw = true, where = cells["_64_"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -3, type = "delta" },
            { y = -5, type = "delta" },
            { x = 55, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -32, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_00_",
            { nodraw = true, where = cells["_73_"]:get_anchor("D"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = -1, type = "delta" },
            { x = 2, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -12, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 16, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "clk",
            { nodraw = true, where = cells["_68_"]:get_anchor("CLK"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -2, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -14, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { z = -1, nodraw = false, type = "via" },
            { nodraw = true, where = cells["_19_reg"]:get_anchor("CLK"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = 1, type = "delta" },
            { x = -35, type = "delta" },
            { y = -1, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_21_reg"]:get_anchor("CLK"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -1, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -9, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = -1, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_70_"]:get_anchor("CLK"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = 1, type = "delta" },
            { x = 2, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { x = 1, type = "delta" },
            { y = -28, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_18_reg"]:get_anchor("CLK"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -13, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -13, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_17_reg"]:get_anchor("CLK"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -5, type = "delta" },
            { y = -1, type = "delta" },
            { x = -9, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -9, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_67_"]:get_anchor("CLK"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = -1, type = "delta" },
            { x = 26, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_66_"]:get_anchor("CLK"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -1, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = 9, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 2, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_14_reg"]:get_anchor("CLK"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -2, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = 14, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_72_"]:get_anchor("CLK"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = -2, type = "delta" },
            { x = -34, type = "delta" },
            { y = 1, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_20_reg"]:get_anchor("CLK"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = 1, type = "delta" },
            { x = -2, type = "delta" },
            { y = 2, type = "delta" },
            { x = 22, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -13, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_12_reg"]:get_anchor("CLK"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = 8, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = -19, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_16_reg"]:get_anchor("CLK"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = 14, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_15_reg"]:get_anchor("CLK"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = 24, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_69_"]:get_anchor("CLK"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = 15, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = -16, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_13_reg"]:get_anchor("CLK"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = -33, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "curr_state_pre_0",
            { nodraw = true, where = cells["_66_"]:get_anchor("Q"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = 8, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -60, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 9, type = "delta" },
            { y = -1, type = "delta" },
            { x = 2, type = "delta" },
            { y = 1, type = "delta" },
            { x = 9, type = "delta" },
            { y = -1, type = "delta" },
            { x = 2, type = "delta" },
            { y = 1, type = "delta" },
            { x = 8, type = "delta" },
            { y = 1, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "curr_state_pre_1",
            { nodraw = true, where = cells["_67_"]:get_anchor("Q"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = 2, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -23, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "curr_state_pre_2",
            { nodraw = true, where = cells["_68_"]:get_anchor("Q"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -3, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { x = -19, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { y = -12, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = -1, type = "delta" },
            { y = 1, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "curr_state_pre_3",
            { nodraw = true, where = cells["_72_"]:get_anchor("D"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = 1, type = "delta" },
            { x = -67, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -26, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = -4, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_01_reg",
            { nodraw = true, where = cells["_05_reg"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { x = -47, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { y = -1, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = -11, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "cmd_reg_3",
            { nodraw = true, where = cells["_06_reg"]:get_anchor("A"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = 13, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -38, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 7, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { nodraw = true, where = cells["_16_reg"]:get_anchor("D"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = 1, type = "delta" },
            { x = 12, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -13, type = "delta" },
            { z = -1, nodraw = true, type = "via" },
            { z = -1, nodraw = true, type = "via" },
            { nodraw = true, where = cells["_20_reg"]:get_anchor("Q"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = 28, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 29, type = "delta" },
            { y = -1, type = "delta" },
            { x = 18, type = "delta" },
            { y = -1, type = "delta" },
            { x = 15, type = "delta" },
        },
        {
            name = "cmd_reg_2",
            { nodraw = true, where = cells["_06_reg"]:get_anchor("B"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -1, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -23, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = -4, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { nodraw = true, where = cells["_09_reg"]:get_anchor("A"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = -39, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 9, type = "delta" },
            { y = 1, type = "delta" },
            { x = 14, type = "delta" },
            { y = 2, type = "delta" },
            { x = 15, type = "delta" },
        },
        {
            name = "_02_reg",
            { nodraw = true, where = cells["_06_reg"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { x = -16, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { y = -35, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = -8, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "cmd_reg_4",
            { nodraw = true, where = cells["_21_reg"]:get_anchor("Q"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -1, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -25, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { z = -1, nodraw = false, type = "via" },
            { nodraw = true, where = cells["_09_reg"]:get_anchor("B"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = 2, type = "delta" },
            { y = -1, type = "delta" },
            { x = 9, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { x = 5, type = "delta" },
            { y = -49, type = "delta" },
        },
        {
            name = "_03_reg",
            { nodraw = true, where = cells["_07_reg"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = 1, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { x = -58, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { z = -1, nodraw = false, type = "via" },
            { x = -10, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_04_reg",
            { nodraw = true, where = cells["_09_reg"]:get_anchor("O"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { x = -8, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -69, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 42, type = "delta" },
            { y = -1, type = "delta" },
            { x = 11, type = "delta" },
            { y = -1, type = "delta" },
            { x = 12, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "_00_reg",
            { nodraw = true, where = cells["_12_reg"]:get_anchor("D"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = -1, type = "delta" },
            { x = -3, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -34, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = -5, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "cmd_reg_pre_0",
            { nodraw = true, where = cells["_17_reg"]:get_anchor("D"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { y = -16, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 30, type = "delta" },
            { y = 1, type = "delta" },
            { x = 6, type = "delta" },
            { y = 1, type = "delta" },
            { x = 11, type = "delta" },
            { y = 1, type = "delta" },
            { x = 3, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "cmd_reg_pre_1",
            { nodraw = true, where = cells["_18_reg"]:get_anchor("D"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { x = 25, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { y = -11, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 3, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "cmd_reg_pre_2",
            { nodraw = true, where = cells["_14_reg"]:get_anchor("Q"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { z = 1, nodraw = false, type = "via" },
            { x = 22, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { y = -37, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "cmd_reg_pre_3",
            { nodraw = true, where = cells["_15_reg"]:get_anchor("Q"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = -3, type = "delta" },
            { x = -104, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = 4, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { z = -1, nodraw = false, type = "via" },
        },
        {
            name = "cmd_reg_pre_4",
            { nodraw = true, where = cells["_16_reg"]:get_anchor("Q"), type = "point" },
            { z = 1, nodraw = false, type = "via" },
            { y = 5, type = "delta" },
            { x = -68, type = "delta" },
            { z = 1, nodraw = false, type = "via" },
            { y = -29, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
            { x = 5, type = "delta" },
            { y = 1, type = "delta" },
            { z = -1, nodraw = false, type = "via" },
        },
    }
    local width = bp.routingwidth
    local xgrid = bp.gspace + bp.glength
    local ygrid = bp.routingwidth + bp.routingspace
    local pnumtracks = bp.pnumtracks
    local nnumtracks = bp.nnumtracks
    local numinnerroutes = bp.numinnerroutes
    routing.route(toplevel, routes, width, numinnerroutes, pnumtracks, nnumtracks, xgrid, ygrid)
end
